var annotated_dup =
[
    [ "doctest", "namespacedoctest.html", [
      [ "LoggingReporter", "structdoctest_1_1LoggingReporter.html", "structdoctest_1_1LoggingReporter" ]
    ] ],
    [ "pairinteraction", "namespacepairinteraction.html", [
      [ "traits", "namespacepairinteraction_1_1traits.html", [
        [ "CrtpTraits", "structpairinteraction_1_1traits_1_1CrtpTraits.html", null ],
        [ "CrtpTraits< BasisAtom< Scalar > >", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01BasisAtom_3_01Scalar_01_4_01_4.html", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01BasisAtom_3_01Scalar_01_4_01_4" ],
        [ "CrtpTraits< BasisPair< Scalar > >", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01BasisPair_3_01Scalar_01_4_01_4.html", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01BasisPair_3_01Scalar_01_4_01_4" ],
        [ "CrtpTraits< OperatorAtom< Scalar > >", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01OperatorAtom_3_01Scalar_01_4_01_4.html", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01OperatorAtom_3_01Scalar_01_4_01_4" ],
        [ "CrtpTraits< OperatorPair< Scalar > >", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01OperatorPair_3_01Scalar_01_4_01_4.html", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01OperatorPair_3_01Scalar_01_4_01_4" ],
        [ "CrtpTraits< SystemAtom< Scalar > >", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01SystemAtom_3_01Scalar_01_4_01_4.html", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01SystemAtom_3_01Scalar_01_4_01_4" ],
        [ "CrtpTraits< SystemPair< Scalar > >", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01SystemPair_3_01Scalar_01_4_01_4.html", "structpairinteraction_1_1traits_1_1CrtpTraits_3_01SystemPair_3_01Scalar_01_4_01_4" ],
        [ "FPTypeTraits", "structpairinteraction_1_1traits_1_1FPTypeTraits.html", null ],
        [ "FPTypeTraits< FloatType::FLOAT32 >", "structpairinteraction_1_1traits_1_1FPTypeTraits_3_01FloatType_1_1FLOAT32_01_4.html", "structpairinteraction_1_1traits_1_1FPTypeTraits_3_01FloatType_1_1FLOAT32_01_4" ],
        [ "FPTypeTraits< FloatType::FLOAT64 >", "structpairinteraction_1_1traits_1_1FPTypeTraits_3_01FloatType_1_1FLOAT64_01_4.html", "structpairinteraction_1_1traits_1_1FPTypeTraits_3_01FloatType_1_1FLOAT64_01_4" ],
        [ "NumTraits", "structpairinteraction_1_1traits_1_1NumTraits.html", "structpairinteraction_1_1traits_1_1NumTraits" ],
        [ "NumTraits< std::complex< Numeric > >", "structpairinteraction_1_1traits_1_1NumTraits_3_01std_1_1complex_3_01Numeric_01_4_01_4.html", "structpairinteraction_1_1traits_1_1NumTraits_3_01std_1_1complex_3_01Numeric_01_4_01_4" ],
        [ "OpTraits", "structpairinteraction_1_1traits_1_1OpTraits.html", null ]
      ] ],
      [ "utils", "namespacepairinteraction_1_1utils.html", [
        [ "hash", "structpairinteraction_1_1utils_1_1hash.html", null ],
        [ "hash< Parity >", "structpairinteraction_1_1utils_1_1hash_3_01Parity_01_4.html", "structpairinteraction_1_1utils_1_1hash_3_01Parity_01_4" ],
        [ "hash< std::array< T, N > >", "structpairinteraction_1_1utils_1_1hash_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", "structpairinteraction_1_1utils_1_1hash_3_01std_1_1array_3_01T_00_01N_01_4_01_4" ],
        [ "hash< std::complex< T > >", "structpairinteraction_1_1utils_1_1hash_3_01std_1_1complex_3_01T_01_4_01_4.html", "structpairinteraction_1_1utils_1_1hash_3_01std_1_1complex_3_01T_01_4_01_4" ],
        [ "hash< std::vector< T > >", "structpairinteraction_1_1utils_1_1hash_3_01std_1_1vector_3_01T_01_4_01_4.html", "structpairinteraction_1_1utils_1_1hash_3_01std_1_1vector_3_01T_01_4_01_4" ]
      ] ],
      [ "AtomDescriptionByParameters", "structpairinteraction_1_1AtomDescriptionByParameters.html", "structpairinteraction_1_1AtomDescriptionByParameters" ],
      [ "AtomDescriptionByRanges", "structpairinteraction_1_1AtomDescriptionByRanges.html", "structpairinteraction_1_1AtomDescriptionByRanges" ],
      [ "Basis", "classpairinteraction_1_1Basis.html", "classpairinteraction_1_1Basis" ],
      [ "BasisAtom", "classpairinteraction_1_1BasisAtom.html", "classpairinteraction_1_1BasisAtom" ],
      [ "BasisAtomCreator", "classpairinteraction_1_1BasisAtomCreator.html", "classpairinteraction_1_1BasisAtomCreator" ],
      [ "BasisPair", "classpairinteraction_1_1BasisPair.html", "classpairinteraction_1_1BasisPair" ],
      [ "BasisPairCreator", "classpairinteraction_1_1BasisPairCreator.html", "classpairinteraction_1_1BasisPairCreator" ],
      [ "Database", "classpairinteraction_1_1Database.html", "classpairinteraction_1_1Database" ],
      [ "database_dir_noexcept", "structpairinteraction_1_1database__dir__noexcept.html", "structpairinteraction_1_1database__dir__noexcept" ],
      [ "DiagonalizerEigen", "classpairinteraction_1_1DiagonalizerEigen.html", "classpairinteraction_1_1DiagonalizerEigen" ],
      [ "DiagonalizerFeast", "classpairinteraction_1_1DiagonalizerFeast.html", "classpairinteraction_1_1DiagonalizerFeast" ],
      [ "DiagonalizerInterface", "classpairinteraction_1_1DiagonalizerInterface.html", "classpairinteraction_1_1DiagonalizerInterface" ],
      [ "DiagonalizerLapackeEvd", "classpairinteraction_1_1DiagonalizerLapackeEvd.html", "classpairinteraction_1_1DiagonalizerLapackeEvd" ],
      [ "DiagonalizerLapackeEvr", "classpairinteraction_1_1DiagonalizerLapackeEvr.html", "classpairinteraction_1_1DiagonalizerLapackeEvr" ],
      [ "EigenSystemH", "structpairinteraction_1_1EigenSystemH.html", "structpairinteraction_1_1EigenSystemH" ],
      [ "GitHubDownloader", "classpairinteraction_1_1GitHubDownloader.html", "classpairinteraction_1_1GitHubDownloader" ],
      [ "GreenTensor", "classpairinteraction_1_1GreenTensor.html", "classpairinteraction_1_1GreenTensor" ],
      [ "IndicesOfBlock", "structpairinteraction_1_1IndicesOfBlock.html", "structpairinteraction_1_1IndicesOfBlock" ],
      [ "IndicesOfBlocksCreator", "classpairinteraction_1_1IndicesOfBlocksCreator.html", "classpairinteraction_1_1IndicesOfBlocksCreator" ],
      [ "Info", "structpairinteraction_1_1Info.html", "structpairinteraction_1_1Info" ],
      [ "Ket", "classpairinteraction_1_1Ket.html", "classpairinteraction_1_1Ket" ],
      [ "KetAtom", "classpairinteraction_1_1KetAtom.html", "classpairinteraction_1_1KetAtom" ],
      [ "KetAtomCreator", "classpairinteraction_1_1KetAtomCreator.html", "classpairinteraction_1_1KetAtomCreator" ],
      [ "KetPair", "classpairinteraction_1_1KetPair.html", "classpairinteraction_1_1KetPair" ],
      [ "MockDownloader", "classpairinteraction_1_1MockDownloader.html", "classpairinteraction_1_1MockDownloader" ],
      [ "Operator", "classpairinteraction_1_1Operator.html", "classpairinteraction_1_1Operator" ],
      [ "OperatorAtom", "classpairinteraction_1_1OperatorAtom.html", "classpairinteraction_1_1OperatorAtom" ],
      [ "OperatorMatrices", "structpairinteraction_1_1OperatorMatrices.html", "structpairinteraction_1_1OperatorMatrices" ],
      [ "OperatorPair", "classpairinteraction_1_1OperatorPair.html", "classpairinteraction_1_1OperatorPair" ],
      [ "overloaded", "structpairinteraction_1_1overloaded.html", null ],
      [ "ParquetManager", "classpairinteraction_1_1ParquetManager.html", "classpairinteraction_1_1ParquetManager" ],
      [ "Range", "classpairinteraction_1_1Range.html", "classpairinteraction_1_1Range" ],
      [ "Sorting", "structpairinteraction_1_1Sorting.html", "structpairinteraction_1_1Sorting" ],
      [ "System", "classpairinteraction_1_1System.html", "classpairinteraction_1_1System" ],
      [ "SystemAtom", "classpairinteraction_1_1SystemAtom.html", "classpairinteraction_1_1SystemAtom" ],
      [ "SystemPair", "classpairinteraction_1_1SystemPair.html", "classpairinteraction_1_1SystemPair" ],
      [ "Transformation", "structpairinteraction_1_1Transformation.html", "structpairinteraction_1_1Transformation" ],
      [ "TransformationBuilderInterface", "classpairinteraction_1_1TransformationBuilderInterface.html", "classpairinteraction_1_1TransformationBuilderInterface" ]
    ] ],
    [ "ConsoleReporter", "classConsoleReporter.html", null ],
    [ "LoggerBridge", "classLoggerBridge.html", "classLoggerBridge" ]
];