pairinteraction: Configuration Class Reference
Configuration Class Reference
Configuration storage
#include <ConfParser.hpp>
Public Types
typedef std::map< std::string, value >::iterator iterator
Iterator type.
typedef std::map< std::string, value >::const_iterator const_iterator
Constant iterator type.
Public Member Functions
void load_from_json (std::string const &filename)
Load configuration from JSON file.
void save_to_json (std::string const &filename) const
Save configuration to JSON file.
Configuration ()=default
Constructor.
size_t count (std::string const &key) const
Number of elements matching specific key.
size_t size () const
Number of elements.
Configuration & operator+= (Configuration const &rhs)
Append operator.
value & operator[] (std::string const &key)
Element access operator.
value operator[] (std::string const &key) const
Constant element access operator.
bool operator== (Configuration const &rhs) const
Comparison operator.
iterator begin ()
Iterator pointing to the beginning.
iterator end ()
Iterator pointing to the end.
const_iterator begin () const
Constant iterator pointing to the beginning.
const_iterator end () const
Constant iterator pointing to the end.
iterator find (std::string const &key)
Find an element associated to a key.
const_iterator find (std::string const &key) const
Constant version of find(std::string const&)
Detailed Description
Configuration storage
This class stores the system configuration. In essence it is a wrapper around a std::map which std::string key and Configuration::value value. The wrapped value class has some advanced features which make it better than a pure std::string value.
Definition at line 35 of file ConfParser.hpp.
Member Typedef Documentation
const_iterator
typedef std::map<std::string, value>::const_iterator Configuration::const_iterator
Constant iterator type.
Instead of implementing an own constant iterator we use the existing one of the underlying std::map.
Definition at line 222 of file ConfParser.hpp.
iterator
typedef std::map<std::string, value>::iterator Configuration::iterator
Iterator type.
Instead of implementing an own iterator we use the existing one of the underlying std::map.
Definition at line 215 of file ConfParser.hpp.
Constructor & Destructor Documentation
Configuration()
Configuration::Configuration () default
Constructor.
Member Function Documentation
begin() [1/2]
iterator Configuration::begin () inline
Iterator pointing to the beginning.
Returns
iterator
Definition at line 228 of file ConfParser.hpp.
begin() [2/2]
const_iterator Configuration::begin () const inline
Constant iterator pointing to the beginning.
Returns
constant iterator
Definition at line 240 of file ConfParser.hpp.
count()
size_t Configuration::count (std::string const & key) const inline
Number of elements matching specific key.
Returns the number of elements matching the key. This can only be zero or one, because the wrapped std::map does not allow duplicates.
Parameters
[in] key Key
Returns
Number of elements machting key
Definition at line 160 of file ConfParser.hpp.
Referenced by compute(), and TEST_CASE().
end() [1/2]
iterator Configuration::end () inline
Iterator pointing to the end.
Returns
iterator
Definition at line 234 of file ConfParser.hpp.
end() [2/2]
const_iterator Configuration::end () const inline
Constant iterator pointing to the end.
Returns
constant iterator
Definition at line 246 of file ConfParser.hpp.
find() [1/2]
iterator Configuration::find (std::string const & key) inline
Find an element associated to a key.
Attempts to find a key in the map and returns an iterator pointing to the element. If no such key exists it returns end().
Returns
iterator
Definition at line 256 of file ConfParser.hpp.
Referenced by TEST_CASE().
find() [2/2]
const_iterator Configuration::find (std::string const & key) const inline
Constant version of find(std::string const&)
Returns
constant iterator
Definition at line 262 of file ConfParser.hpp.
load_from_json()
void Configuration::load_from_json (std::string const & filename)
Load configuration from JSON file.
Loads the configuration from a JSON file using Boost's ptree.
Parameters
[in] filename Path to the JSON file
Definition at line 25 of file ConfParser.cpp.
Referenced by HamiltonianOne< Scalar >::build(), HamiltonianTwo< Scalar >::calculate(), and compute().
operator+=()
Configuration& Configuration::operator+= (Configuration const & rhs) inline
Append operator.
This will append the right hand side to the left hand side. If a key exists on both sides, it will be overwritten with the value from the right hand side.
Returns
Configuration appended to
Definition at line 176 of file ConfParser.hpp.
operator==()
bool Configuration::operator== (Configuration const & rhs) const inline
Comparison operator.
Compares two configurations.
Returns
Truth value for equality
Definition at line 208 of file ConfParser.hpp.
operator[]() [1/2]
value& Configuration::operator[] (std::string const & key) inline
Element access operator.
This returns a reference to the element associated to the key and will insert it if no such key exists.
Returns
Reference to the value
Definition at line 190 of file ConfParser.hpp.
operator[]() [2/2]
value Configuration::operator[] (std::string const & key) const inline
Constant element access operator.
This returns a copy of the element associated to the key. It throws if no such key exists.
Returns
Copy of the value
Exceptions
std::out_of_range
Definition at line 200 of file ConfParser.hpp.
save_to_json()
void Configuration::save_to_json (std::string const & filename) const
Save configuration to JSON file.
Saves the configuration to a JSON file using Boost's ptree.
Parameters
[in] filename Path to the JSON file
Definition at line 37 of file ConfParser.cpp.
size()
size_t Configuration::size () const inline
Number of elements.
Returns
Number of elements
Definition at line 166 of file ConfParser.hpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/ConfParser.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/ConfParser.cpp