pairinteraction: pairinteraction::BasisAtomCreator< Scalar > Class Template Reference
pairinteraction::BasisAtomCreator< Scalar > Class Template Reference
Builder class for creating BasisAtom objects.
#include <BasisAtomCreator.hpp>
Public Types
using real_t = typename traits::NumTraits< Scalar >::real_t
using ket_t = KetAtom
Public Member Functions
BasisAtomCreator ()=default
BasisAtomCreator< Scalar > & set_species (const std::string &value)
BasisAtomCreator< Scalar > & restrict_energy (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_f (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_m (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_parity (Parity value)
BasisAtomCreator< Scalar > & restrict_quantum_number_n (int min, int max)
BasisAtomCreator< Scalar > & restrict_quantum_number_nu (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_nui (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_l (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_s (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_j (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_l_ryd (real_t min, real_t max)
BasisAtomCreator< Scalar > & restrict_quantum_number_j_ryd (real_t min, real_t max)
BasisAtomCreator< Scalar > & append_ket (const std::shared_ptr< const ket_t > &ket)
std::shared_ptr< const BasisAtom< Scalar > > create (Database &database) const
Detailed Description
template<typename Scalar>
class pairinteraction::BasisAtomCreator< Scalar >
Builder class for creating BasisAtom objects.
Template Parameters
Scalar Complex number type.
Definition at line 32 of file BasisAtomCreator.hpp.
Member Typedef Documentation
ket_t
template<typename Scalar > using pairinteraction::BasisAtomCreator< Scalar >::ket_t = KetAtom
Definition at line 37 of file BasisAtomCreator.hpp.
real_t
template<typename Scalar > using pairinteraction::BasisAtomCreator< Scalar >::real_t = typename traits::NumTraits<Scalar>::real_t
Definition at line 36 of file BasisAtomCreator.hpp.
Constructor & Destructor Documentation
BasisAtomCreator()
template<typename Scalar > pairinteraction::BasisAtomCreator< Scalar >::BasisAtomCreator () default
Member Function Documentation
append_ket()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::append_ket (const std::shared_ptr< const ket_t > & ket)
Definition at line 107 of file BasisAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
create()
template<typename Scalar > std::shared_ptr< const BasisAtom< Scalar > > pairinteraction::BasisAtomCreator< Scalar >::create (Database & database) const
Definition at line 119 of file BasisAtomCreator.cpp.
References pairinteraction::Database::get_basis().
restrict_energy()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_energy (real_t min, real_t max)
Definition at line 19 of file BasisAtomCreator.cpp.
restrict_parity()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_parity (Parity value)
Definition at line 45 of file BasisAtomCreator.cpp.
restrict_quantum_number_f()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_f (real_t min, real_t max)
Definition at line 25 of file BasisAtomCreator.cpp.
restrict_quantum_number_j()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_j (real_t min, real_t max)
Definition at line 85 of file BasisAtomCreator.cpp.
restrict_quantum_number_j_ryd()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_j_ryd (real_t min, real_t max)
Definition at line 99 of file BasisAtomCreator.cpp.
restrict_quantum_number_l()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_l (real_t min, real_t max)
Definition at line 71 of file BasisAtomCreator.cpp.
restrict_quantum_number_l_ryd()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_l_ryd (real_t min, real_t max)
Definition at line 92 of file BasisAtomCreator.cpp.
restrict_quantum_number_m()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_m (real_t min, real_t max)
Definition at line 35 of file BasisAtomCreator.cpp.
restrict_quantum_number_n()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_n (int min, int max)
Definition at line 51 of file BasisAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
restrict_quantum_number_nu()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_nu (real_t min, real_t max)
Definition at line 57 of file BasisAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE().
restrict_quantum_number_nui()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_nui (real_t min, real_t max)
Definition at line 64 of file BasisAtomCreator.cpp.
restrict_quantum_number_s()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::restrict_quantum_number_s (real_t min, real_t max)
Definition at line 78 of file BasisAtomCreator.cpp.
set_species()
template<typename Scalar > BasisAtomCreator< Scalar > & pairinteraction::BasisAtomCreator< Scalar >::set_species (const std::string & value)
Definition at line 13 of file BasisAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/basis/BasisAtomCreator.hpp
/__w/pairinteraction/pairinteraction/src/cpp/src/basis/BasisAtomCreator.cpp