pairinteraction: pairinteraction::ParquetManager Class Reference
pairinteraction::ParquetManager Class Reference
#include <ParquetManager.hpp>
Data Structures
struct LocalAssetInfo
struct PathInfo
struct RemoteAssetInfo
Public Member Functions
ParquetManager (std::filesystem::path directory, const GitHubDownloader &downloader, std::vector< std::string > repo_paths, duckdb::Connection &con, bool use_cache)
void scan_local ()
void scan_remote ()
std::string get_path (const std::string &key, const std::string &table)
std::string get_versions_info () const
Detailed Description
Definition at line 21 of file ParquetManager.hpp.
Constructor & Destructor Documentation
ParquetManager()
pairinteraction::ParquetManager::ParquetManager (std::filesystem::path directory, const GitHubDownloader & downloader, std::vector< std::string > repo_paths, duckdb::Connection & con, bool use_cache)
Definition at line 54 of file ParquetManager.cpp.
References format_time(), and pairinteraction::GitHubDownloader::get_rate_limit().
Member Function Documentation
get_path()
std::string pairinteraction::ParquetManager::get_path (const std::string & key, const std::string & table)
Definition at line 370 of file ParquetManager.cpp.
Referenced by pairinteraction::TEST_CASE().
get_versions_info()
std::string pairinteraction::ParquetManager::get_versions_info () const
Definition at line 396 of file ParquetManager.cpp.
References pairinteraction::COMPATIBLE_DATABASE_VERSION_MAJOR.
Referenced by pairinteraction::DOCTEST_TEST_CASE().
scan_local()
void pairinteraction::ParquetManager::scan_local ()
Definition at line 182 of file ParquetManager.cpp.
References pairinteraction::COMPATIBLE_DATABASE_VERSION_MAJOR.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and pairinteraction::TEST_CASE().
scan_remote()
void pairinteraction::ParquetManager::scan_remote ()
Definition at line 76 of file ParquetManager.cpp.
References pairinteraction::COMPATIBLE_DATABASE_VERSION_MAJOR, pairinteraction::GitHubDownloader::download(), pairinteraction::GitHubDownloader::get_host(), load_json(), and save_json().
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and pairinteraction::TEST_CASE().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/database/ParquetManager.hpp
/__w/pairinteraction/pairinteraction/src/cpp/src/database/ParquetManager.cpp