pairinteraction: pairinteraction::GitHubDownloader Class Reference
pairinteraction::GitHubDownloader Class Reference
#include <GitHubDownloader.hpp>
Data Structures
struct RateLimit
class Result
Public Member Functions
GitHubDownloader ()
virtual ~GitHubDownloader ()
virtual std::future< Result > download (const std::string &remote_url, const std::string &if_modified_since="", bool use_octet_stream=false) const
RateLimit get_rate_limit () const
std::string get_host () const
Detailed Description
Definition at line 16 of file GitHubDownloader.hpp.
Constructor & Destructor Documentation
GitHubDownloader()
pairinteraction::GitHubDownloader::GitHubDownloader ()
Definition at line 17 of file GitHubDownloader.cpp.
References pairinteraction::paths::get_config_directory().
~GitHubDownloader()
pairinteraction::GitHubDownloader::~GitHubDownloader () virtual default
Member Function Documentation
download()
std::future< GitHubDownloader::Result > pairinteraction::GitHubDownloader::download (const std::string & remote_url, const std::string & if_modified_since = "", bool use_octet_stream = false) const virtual
Reimplemented in pairinteraction::MockDownloader.
Definition at line 47 of file GitHubDownloader.cpp.
References pairinteraction::GitHubDownloader::Result::body, pairinteraction::GitHubDownloader::Result::last_modified, pairinteraction::GitHubDownloader::Result::rate_limit, pairinteraction::GitHubDownloader::RateLimit::remaining, pairinteraction::GitHubDownloader::RateLimit::reset_time, and pairinteraction::GitHubDownloader::Result::status_code.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and pairinteraction::ParquetManager::scan_remote().
get_host()
std::string pairinteraction::GitHubDownloader::get_host () const
Definition at line 112 of file GitHubDownloader.cpp.
Referenced by pairinteraction::ParquetManager::scan_remote().
get_rate_limit()
GitHubDownloader::RateLimit pairinteraction::GitHubDownloader::get_rate_limit () const
Definition at line 102 of file GitHubDownloader.cpp.
References pairinteraction::GitHubDownloader::Result::rate_limit, and pairinteraction::GitHubDownloader::Result::status_code.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and pairinteraction::ParquetManager::ParquetManager().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/database/GitHubDownloader.hpp
/__w/pairinteraction/pairinteraction/src/cpp/src/database/GitHubDownloader.cpp