pairinteraction: PerturbativeInteraction Class Reference
PerturbativeInteraction Class Reference
#include <PerturbativeInteraction.hpp>
Public Member Functions
PerturbativeInteraction (MatrixElementCache &cache)
PerturbativeInteraction (double angle, MatrixElementCache &cache)
double getC6 (const StateTwo &state, double deltaN)
Eigen::MatrixX< double > getC6 (const std::vector< StateTwo > &states, double deltaN)
Eigen::MatrixX< double > getC3 (const std::vector< StateTwo > &states)
Eigen::MatrixX< double > getEnergy (const std::vector< StateTwo > &states)
Detailed Description
Definition at line 29 of file PerturbativeInteraction.hpp.
Constructor & Destructor Documentation
PerturbativeInteraction() [1/2]
PerturbativeInteraction::PerturbativeInteraction (MatrixElementCache & cache)
Definition at line 30 of file PerturbativeInteraction.cpp.
PerturbativeInteraction() [2/2]
PerturbativeInteraction::PerturbativeInteraction (double angle, MatrixElementCache & cache)
Definition at line 34 of file PerturbativeInteraction.cpp.
Member Function Documentation
getC3()
Eigen::MatrixX< double > PerturbativeInteraction::getC3 (const std::vector< StateTwo > & states)
Definition at line 292 of file PerturbativeInteraction.cpp.
References coulombs_constant, and MatrixElementCache::getElectricDipole().
getC6() [1/2]
double PerturbativeInteraction::getC6 (const StateTwo & state, double deltaN)
Definition at line 39 of file PerturbativeInteraction.cpp.
References coulombs_constant, MatrixElementCache::getElectricDipole(), StateTwo::getEnergy(), StateTwo::getFirstState(), StateTwo::getJ(), StateTwo::getL(), StateTwo::getM(), StateTwo::getN(), StateTwo::getS(), StateTwo::getSecondState(), and StateTwo::getSpecies().
getC6() [2/2]
Eigen::MatrixX< double > PerturbativeInteraction::getC6 (const std::vector< StateTwo > & states, double deltaN)
Definition at line 135 of file PerturbativeInteraction.cpp.
References coulombs_constant, MatrixElementCache::getElectricDipole(), StateTwo::getEnergy(), StateTwo::getFirstState(), and StateTwo::getSecondState().
getEnergy()
Eigen::MatrixX< double > PerturbativeInteraction::getEnergy (const std::vector< StateTwo > & states)
Definition at line 321 of file PerturbativeInteraction.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/PerturbativeInteraction.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/PerturbativeInteraction.cpp