pairinteraction: SystemOne< Scalar_ > Class Template Reference
SystemOne< Scalar_ > Class Template Reference
#include <SystemOne.hpp>
Public Types
using Scalar = Scalar_
Public Member Functions
SystemOne (std::string species, MatrixElementCache &cache)
SystemOne (std::string species, MatrixElementCache &cache, bool memory_saving)
const std::string & getSpecies () const
void setEfield (std::array< double, 3 > field)
void setBfield (std::array< double, 3 > field)
void setEfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void setBfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void setEfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
void setBfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
void enableDiamagnetism (bool enable)
void setIonCharge (int c)
void setRydIonOrder (unsigned int o)
void setRydIonDistance (double d)
void setConservedParityUnderReflection (parity_t parity)
void setConservedMomentaUnderRotation (const std::set< float > &momenta)
Public Member Functions inherited from SystemBase< Scalar_, StateOne >
virtual ~SystemBase ()=default
void setMinimalNorm (const double &threshold)
void restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
void restrictN (int n_min, int n_max)
void restrictN (std::set< int > n)
void restrictL (int l_min, int l_max)
void restrictL (std::set< int > l)
void restrictJ (float j_min, float j_max)
void restrictJ (std::set< float > j)
void restrictM (float m_min, float m_max)
void restrictM (std::set< float > m)
void addStates (const StateOne &s)
Method for adding user-defined states //////////////////////////.
void addStates (const std::set< StateOne > &s)
Eigen::VectorX< double > getOverlap (const StateOne &generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
Eigen::VectorX< double > getOverlap (const std::vector< StateOne > &generalizedstates)
Eigen::VectorX< double > getOverlap (const size_t &state_index)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices)
Eigen::VectorX< double > getOverlap (const StateOne &generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const std::vector< StateOne > &generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const size_t &state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const StateOne &generalizedstate, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const size_t &state_index, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const std::vector< StateOne > &generalizedstates, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)
std::vector< StateOne > getStates ()
Methods to get properties of the system ////////////////////////.
const states_set< StateOne >::type & getStatesMultiIndex ()
Eigen::SparseMatrix< Scalar_ > & getBasisvectors ()
Eigen::SparseMatrix< Scalar_ > & getHamiltonian ()
size_t getNumBasisvectors ()
size_t getNumStates ()
std::vector< StateOne > getMainStates ()
std::array< std::vector< size_t >, 2 > getConnections (SystemBase< Scalar_, StateOne > &system_to, double threshold)
void buildHamiltonian ()
Methods to build, transform, and destroy the system ////////////.
void buildInteraction ()
void buildBasis ()
void diagonalize (double energy_lower_bound, double energy_upper_bound)
void diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
void diagonalize ()
void diagonalize (double threshold)
void canonicalize ()
void unitarize ()
void rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void rotate (double alpha, double beta, double gamma)
void add (SystemBase< Scalar_, StateOne > &system)
void constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
void applySchriefferWolffTransformation (SystemBase< Scalar_, StateOne > &system0)
size_t getStateIndex (const StateOne &searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
std::vector< size_t > getStateIndex (const std::vector< StateOne > &searched_states)
size_t getBasisvectorIndex (const StateOne &searched_state)
std::vector< size_t > getBasisvectorIndex (const std::vector< StateOne > &searched_states)
void forgetStatemixing ()
Scalar_ getHamiltonianEntry (const StateOne &state_row, const StateOne &state_col)
void setHamiltonianEntry (const StateOne &state_row, const StateOne &state_col, Scalar_ value)
void addHamiltonianEntry (const StateOne &state_row, const StateOne &state_col, Scalar_ value)
Protected Member Functions
void initializeBasis () override
Method that allows base class to initialize Basis //////////////.
void initializeInteraction () override
Method that allows base class to calculate the interaction /////.
void addInteraction () override
Method that allows base class to construct Hamiltonian /////////.
void transformInteraction (const Eigen::SparseMatrix< Scalar_ > &transformator) override
Method that allows base class to transform the interaction /////.
void deleteInteraction () override
Method that allows base class to delete the interaction ////////.
Eigen::SparseMatrix< Scalar_ > rotateStates (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma) override
Methods that allows base class to rotate states ////////////////.
Eigen::SparseMatrix< Scalar_ > buildStaterotator (double alpha, double beta, double gamma) override
void incorporate (SystemBase< Scalar_, StateOne > &system) override
Method that allows base class to combine systems ///////////////.
Protected Member Functions inherited from SystemBase< Scalar_, StateOne >
SystemBase ()
SystemBase (MatrixElementCache &cache)
SystemBase (MatrixElementCache &cache, bool memory_saving)
virtual void onStatesChange ()
void onParameterChange ()
Helper method that shoul be called by the derived classes //////.
void onSymmetryChange ()
bool checkIsDiagonal (const Eigen::SparseMatrix< Scalar_ > &mat)
Helper methods to check diagonality and unitarity of a matrix //.
bool checkIsUnitary (const Eigen::SparseMatrix< Scalar_ > &mat)
bool checkIsQuantumnumberValid (V q, std::set< V > range_q)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateOne &state)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateOne &state, bool a)
bool checkIsQuantumstateValid (const StateTwo &state, std::array< bool, 2 > a)
bool checkIsEnergyValid (double e)
void applyLeftsideTransformator (std::vector< Eigen::Triplet< Scalar_ >> &triplets_transformator)
Helper methods to change the set of basis vectors //////////////.
void applyLeftsideTransformator (Eigen::SparseMatrix< Scalar_ > &transformator)
void applyRightsideTransformator (std::vector< Eigen::Triplet< Scalar_ >> &triplets_transformator)
void applyRightsideTransformator (Eigen::SparseMatrix< Scalar_ > &transformator)
void removeRestrictedStates (std::function< bool(const enumerated_state< StateOne > &)> checkIsValidEntry)
void range (std::set< V > &rset, V rmin, V rmax)
Utility methods ////////////////////////////////////////////////.
Eigen::Matrix< double, 3, 3 > buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Utility methods ////////////////////////////////////////////////.
Eigen::Matrix< double, 3, 3 > buildRotator (const double &alpha, const double &beta, const double &gamma)
Eigen::Matrix< double, 3, 1 > getEulerAngles (const std::array< double, 3 > &to_z_axis, const std::array< double, 3 > &to_y_axis)
Friends
class cereal::access
Method for serialization ///////////////////////////////////////.
class SystemTwo< Scalar_ >
Additional Inherited Members
Protected Attributes inherited from SystemBase< Scalar_, StateOne >
MatrixElementCache * m_cache
double threshold_for_sqnorm
double energy_min
double energy_max
std::set< int > range_n
std::set< int > range_l
std::set< float > range_j
std::set< float > range_m
std::set< StateOne > states_to_add
bool memory_saving
bool is_interaction_already_contained
bool is_new_hamiltonian_required
states_set< StateOne >::type states
Eigen::SparseMatrix< Scalar_ > basisvectors
Eigen::SparseMatrix< Scalar_ > hamiltonian
Eigen::SparseMatrix< Scalar_ > basisvectors_unperturbed_cache
Eigen::SparseMatrix< Scalar_ > hamiltonian_unperturbed_cache
Detailed Description
template<typename Scalar_>
class SystemOne< Scalar_ >
Definition at line 43 of file SystemOne.hpp.
Member Typedef Documentation
Scalar
template<typename Scalar_ > using SystemOne< Scalar_ >::Scalar = Scalar_
Definition at line 45 of file SystemOne.hpp.
Constructor & Destructor Documentation
SystemOne() [1/2]
template<typename Scalar > SystemOne< Scalar >::SystemOne (std::string species, MatrixElementCache & cache)
Definition at line 40 of file SystemOne.cpp.
SystemOne() [2/2]
template<typename Scalar > SystemOne< Scalar >::SystemOne (std::string species, MatrixElementCache & cache, bool memory_saving)
Definition at line 46 of file SystemOne.cpp.
Member Function Documentation
addInteraction()
template<typename Scalar > void SystemOne< Scalar >::addInteraction override protected virtual
Method that allows base class to construct Hamiltonian /////////.
Implements SystemBase< Scalar_, StateOne >.
Definition at line 576 of file SystemOne.cpp.
buildStaterotator()
template<typename Scalar > Eigen::SparseMatrix< Scalar > SystemOne< Scalar >::buildStaterotator (double alpha, double beta, double gamma) override protected virtual
Implements SystemBase< Scalar_, StateOne >.
Definition at line 692 of file SystemOne.cpp.
deleteInteraction()
template<typename Scalar > void SystemOne< Scalar >::deleteInteraction override protected virtual
Method that allows base class to delete the interaction ////////.
Implements SystemBase< Scalar_, StateOne >.
Definition at line 654 of file SystemOne.cpp.
enableDiamagnetism()
template<typename Scalar > void SystemOne< Scalar >::enableDiamagnetism (bool enable)
Definition at line 112 of file SystemOne.cpp.
Referenced by TEST_CASE_FIXTURE().
getSpecies()
template<typename Scalar > const std::string & SystemOne< Scalar >::getSpecies
Definition at line 52 of file SystemOne.cpp.
Referenced by SystemTwo< Scalar_ >::SystemTwo().
incorporate()
template<typename Scalar > void SystemOne< Scalar >::incorporate (SystemBase< Scalar_, StateOne > & system) override protected virtual
Method that allows base class to combine systems ///////////////.
Implements SystemBase< Scalar_, StateOne >.
Definition at line 719 of file SystemOne.cpp.
References ARB, and NA.
initializeBasis()
template<typename Scalar > void SystemOne< Scalar >::initializeBasis override protected virtual
Method that allows base class to initialize Basis //////////////.
Build one atom states //////////////////////////////////////////
Loop over specified quantum numbers ////////////////////////////
Loop over user-defined states //////////////////////////////////
Build data /////////////////////////////////////////////////////
Implements SystemBase< Scalar_, StateOne >.
Definition at line 163 of file SystemOne.cpp.
References ARB, StateOne::getEnergy(), StateOne::getM(), and NA.
initializeInteraction()
template<typename Scalar > void SystemOne< Scalar >::initializeInteraction override protected virtual
Method that allows base class to calculate the interaction /////.
Prepare the calculation of the interaction /////////////////////
Calculate the interaction in the canonical basis ///////////////
Build and transform the interaction to the used basis //////////
Implements SystemBase< Scalar_, StateOne >.
Definition at line 338 of file SystemOne.cpp.
References coulombs_constant, electron_rest_mass, elementary_charge, selectionRulesMomentumNew(), and selectionRulesMultipoleNew().
rotateStates()
template<typename Scalar > Eigen::SparseMatrix< Scalar > SystemOne< Scalar >::rotateStates (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) override protected virtual
Methods that allows base class to rotate states ////////////////.
Implements SystemBase< Scalar_, StateOne >.
Definition at line 667 of file SystemOne.cpp.
setBfield() [1/3]
template<typename Scalar > void SystemOne< Scalar >::setBfield (std::array< double, 3 > field)
Definition at line 66 of file SystemOne.cpp.
Referenced by TEST_CASE_FIXTURE().
setBfield() [2/3]
template<typename Scalar > void SystemOne< Scalar >::setBfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
Definition at line 105 of file SystemOne.cpp.
setBfield() [3/3]
template<typename Scalar > void SystemOne< Scalar >::setBfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 91 of file SystemOne.cpp.
setConservedMomentaUnderRotation()
template<typename Scalar > void SystemOne< Scalar >::setConservedMomentaUnderRotation (const std::set< float > & momenta)
Definition at line 145 of file SystemOne.cpp.
References ARB.
setConservedParityUnderReflection()
template<typename Scalar > void SystemOne< Scalar >::setConservedParityUnderReflection (parity_t parity)
Definition at line 135 of file SystemOne.cpp.
setEfield() [1/3]
template<typename Scalar > void SystemOne< Scalar >::setEfield (std::array< double, 3 > field)
Definition at line 57 of file SystemOne.cpp.
Referenced by TEST_CASE_FIXTURE().
setEfield() [2/3]
template<typename Scalar > void SystemOne< Scalar >::setEfield (std::array< double, 3 > field, double alpha, double beta, double gamma)
Definition at line 98 of file SystemOne.cpp.
setEfield() [3/3]
template<typename Scalar > void SystemOne< Scalar >::setEfield (std::array< double, 3 > field, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 84 of file SystemOne.cpp.
setIonCharge()
template<typename Scalar > void SystemOne< Scalar >::setIonCharge (int c)
Definition at line 117 of file SystemOne.cpp.
setRydIonDistance()
template<typename Scalar > void SystemOne< Scalar >::setRydIonDistance (double d)
Definition at line 129 of file SystemOne.cpp.
setRydIonOrder()
template<typename Scalar > void SystemOne< Scalar >::setRydIonOrder (unsigned int o)
Definition at line 123 of file SystemOne.cpp.
transformInteraction()
template<typename Scalar > void SystemOne< Scalar >::transformInteraction (const Eigen::SparseMatrix< Scalar_ > & transformator) override protected virtual
Method that allows base class to transform the interaction /////.
Implements SystemBase< Scalar_, StateOne >.
Definition at line 634 of file SystemOne.cpp.
Friends And Related Function Documentation
cereal::access
template<typename Scalar_ > friend class cereal::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 164 of file SystemOne.hpp.
SystemTwo< Scalar_ >
template<typename Scalar_ > friend class SystemTwo< Scalar_ > friend
Definition at line 164 of file SystemOne.hpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/SystemOne.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/SystemOne.cpp