pairinteraction: SystemTwo< Scalar_ > Class Template Reference
SystemTwo< Scalar_ > Class Template Reference
#include <SystemTwo.hpp>
Public Types
using Scalar = Scalar_
Public Member Functions
SystemTwo (const SystemOne< Scalar_ > &b1, const SystemOne< Scalar_ > &b2, MatrixElementCache &cache)
SystemTwo (const SystemOne< Scalar_ > &b1, const SystemOne< Scalar_ > &b2, MatrixElementCache &cache, bool memory_saving)
const std::array< std::string, 2 > & getSpecies ()
std::vector< StateOne > getStatesFirst ()
std::vector< StateOne > getStatesSecond ()
void enableGreenTensor (bool GTboolean)
void setSurfaceDistance (double d)
void setAngle (double a)
void setDistance (double d)
void setDistanceVector (std::array< double, 3 > d)
void setOrder (double o)
void setConservedParityUnderPermutation (parity_t parity)
void setConservedParityUnderInversion (parity_t parity)
void setConservedParityUnderReflection (parity_t parity)
void setConservedMomentaUnderRotation (const std::set< int > &momenta)
void setOneAtomBasisvectors (const std::vector< std::array< size_t, 2 >> &indices)
Public Member Functions inherited from SystemBase< Scalar_, StateTwo >
virtual ~SystemBase ()=default
void setMinimalNorm (const double &threshold)
void restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
void restrictN (int n_min, int n_max)
void restrictN (std::set< int > n)
void restrictL (int l_min, int l_max)
void restrictL (std::set< int > l)
void restrictJ (float j_min, float j_max)
void restrictJ (std::set< float > j)
void restrictM (float m_min, float m_max)
void restrictM (std::set< float > m)
void addStates (const StateTwo &s)
Method for adding user-defined states //////////////////////////.
void addStates (const std::set< StateTwo > &s)
Eigen::VectorX< double > getOverlap (const StateTwo &generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
Eigen::VectorX< double > getOverlap (const std::vector< StateTwo > &generalizedstates)
Eigen::VectorX< double > getOverlap (const size_t &state_index)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices)
Eigen::VectorX< double > getOverlap (const StateTwo &generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const std::vector< StateTwo > &generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const size_t &state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const StateTwo &generalizedstate, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const size_t &state_index, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const std::vector< StateTwo > &generalizedstates, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)
std::vector< StateTwo > getStates ()
Methods to get properties of the system ////////////////////////.
const states_set< StateTwo >::type & getStatesMultiIndex ()
Eigen::SparseMatrix< Scalar_ > & getBasisvectors ()
Eigen::SparseMatrix< Scalar_ > & getHamiltonian ()
size_t getNumBasisvectors ()
size_t getNumStates ()
std::vector< StateTwo > getMainStates ()
std::array< std::vector< size_t >, 2 > getConnections (SystemBase< Scalar_, StateTwo > &system_to, double threshold)
void buildHamiltonian ()
Methods to build, transform, and destroy the system ////////////.
void buildInteraction ()
void buildBasis ()
void diagonalize (double energy_lower_bound, double energy_upper_bound)
void diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
void diagonalize ()
void diagonalize (double threshold)
void canonicalize ()
void unitarize ()
void rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void rotate (double alpha, double beta, double gamma)
void add (SystemBase< Scalar_, StateTwo > &system)
void constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
void applySchriefferWolffTransformation (SystemBase< Scalar_, StateTwo > &system0)
size_t getStateIndex (const StateTwo &searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
std::vector< size_t > getStateIndex (const std::vector< StateTwo > &searched_states)
size_t getBasisvectorIndex (const StateTwo &searched_state)
std::vector< size_t > getBasisvectorIndex (const std::vector< StateTwo > &searched_states)
void forgetStatemixing ()
Scalar_ getHamiltonianEntry (const StateTwo &state_row, const StateTwo &state_col)
void setHamiltonianEntry (const StateTwo &state_row, const StateTwo &state_col, Scalar_ value)
void addHamiltonianEntry (const StateTwo &state_row, const StateTwo &state_col, Scalar_ value)
Protected Member Functions
void initializeBasis () override
Method that allows base class to initialize Basis //////////////.
void initializeInteraction () override
Method that allows base class to calculate the interaction /////.
void addInteraction () override
Method that allows base class to construct Hamiltonian /////////.
void transformInteraction (const Eigen::SparseMatrix< Scalar_ > &transformator) override
Method that allows base class to transform the interaction /////.
void deleteInteraction () override
Method that allows base class to delete the interaction ////////.
Eigen::SparseMatrix< Scalar_ > rotateStates (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma) override
Methods that allows base class to rotate states ////////////////.
Eigen::SparseMatrix< Scalar_ > buildStaterotator (double alpha, double beta, double gamma) override
void incorporate (SystemBase< Scalar_, StateTwo > &system) override
Method that allows base class to combine systems ///////////////.
void onStatesChange () override
Methods that allows base class to communicate with subclass ////.
Protected Member Functions inherited from SystemBase< Scalar_, StateTwo >
SystemBase ()
SystemBase (MatrixElementCache &cache)
SystemBase (MatrixElementCache &cache, bool memory_saving)
void onParameterChange ()
Helper method that shoul be called by the derived classes //////.
void onSymmetryChange ()
bool checkIsDiagonal (const Eigen::SparseMatrix< Scalar_ > &mat)
Helper methods to check diagonality and unitarity of a matrix //.
bool checkIsUnitary (const Eigen::SparseMatrix< Scalar_ > &mat)
bool checkIsQuantumnumberValid (V q, std::set< V > range_q)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateTwo &state)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateOne &state, bool a)
bool checkIsQuantumstateValid (const StateTwo &state, std::array< bool, 2 > a)
bool checkIsEnergyValid (double e)
void applyLeftsideTransformator (std::vector< Eigen::Triplet< Scalar_ >> &triplets_transformator)
Helper methods to change the set of basis vectors //////////////.
void applyLeftsideTransformator (Eigen::SparseMatrix< Scalar_ > &transformator)
void applyRightsideTransformator (std::vector< Eigen::Triplet< Scalar_ >> &triplets_transformator)
void applyRightsideTransformator (Eigen::SparseMatrix< Scalar_ > &transformator)
void removeRestrictedStates (std::function< bool(const enumerated_state< StateTwo > &)> checkIsValidEntry)
void range (std::set< V > &rset, V rmin, V rmax)
Utility methods ////////////////////////////////////////////////.
Eigen::Matrix< double, 3, 3 > buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Utility methods ////////////////////////////////////////////////.
Eigen::Matrix< double, 3, 3 > buildRotator (const double &alpha, const double &beta, const double &gamma)
Eigen::Matrix< double, 3, 1 > getEulerAngles (const std::array< double, 3 > &to_z_axis, const std::array< double, 3 > &to_y_axis)
Friends
class cereal::access
Method for serialization ///////////////////////////////////////.
Additional Inherited Members
Protected Attributes inherited from SystemBase< Scalar_, StateTwo >
MatrixElementCache * m_cache
double threshold_for_sqnorm
double energy_min
double energy_max
std::set< int > range_n
std::set< int > range_l
std::set< float > range_j
std::set< float > range_m
std::set< StateTwo > states_to_add
bool memory_saving
bool is_interaction_already_contained
bool is_new_hamiltonian_required
states_set< StateTwo >::type states
Eigen::SparseMatrix< Scalar_ > basisvectors
Eigen::SparseMatrix< Scalar_ > hamiltonian
Eigen::SparseMatrix< Scalar_ > basisvectors_unperturbed_cache
Eigen::SparseMatrix< Scalar_ > hamiltonian_unperturbed_cache
Detailed Description
template<typename Scalar_>
class SystemTwo< Scalar_ >
Definition at line 41 of file SystemTwo.hpp.
Member Typedef Documentation
Scalar
template<typename Scalar_ > using SystemTwo< Scalar_ >::Scalar = Scalar_
Definition at line 43 of file SystemTwo.hpp.
Constructor & Destructor Documentation
SystemTwo() [1/2]
template<typename Scalar > SystemTwo< Scalar >::SystemTwo (const SystemOne< Scalar_ > & b1, const SystemOne< Scalar_ > & b2, MatrixElementCache & cache)
Definition at line 42 of file SystemTwo.cpp.
References SystemOne< Scalar_ >::getSpecies().
SystemTwo() [2/2]
template<typename Scalar > SystemTwo< Scalar >::SystemTwo (const SystemOne< Scalar_ > & b1, const SystemOne< Scalar_ > & b2, MatrixElementCache & cache, bool memory_saving)
Definition at line 52 of file SystemTwo.cpp.
References SystemOne< Scalar_ >::getSpecies().
Member Function Documentation
addInteraction()
template<typename Scalar > void SystemTwo< Scalar >::addInteraction override protected virtual
Method that allows base class to construct Hamiltonian /////////.
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 1337 of file SystemTwo.cpp.
References model_potential::g().
buildStaterotator()
template<typename Scalar > Eigen::SparseMatrix< Scalar > SystemTwo< Scalar >::buildStaterotator (double alpha, double beta, double gamma) override protected virtual
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 1434 of file SystemTwo.cpp.
deleteInteraction()
template<typename Scalar > void SystemTwo< Scalar >::deleteInteraction override protected virtual
Method that allows base class to delete the interaction ////////.
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 1394 of file SystemTwo.cpp.
enableGreenTensor()
template<typename Scalar > void SystemTwo< Scalar >::enableGreenTensor (bool GTboolean)
Definition at line 90 of file SystemTwo.cpp.
getSpecies()
template<typename Scalar > const std::array< std::string, 2 > & SystemTwo< Scalar >::getSpecies
Definition at line 85 of file SystemTwo.cpp.
getStatesFirst()
template<typename Scalar > std::vector< StateOne > SystemTwo< Scalar >::getStatesFirst
Definition at line 64 of file SystemTwo.cpp.
getStatesSecond()
template<typename Scalar > std::vector< StateOne > SystemTwo< Scalar >::getStatesSecond
Definition at line 75 of file SystemTwo.cpp.
incorporate()
template<typename Scalar > void SystemTwo< Scalar >::incorporate (SystemBase< Scalar_, StateTwo > & system) override protected virtual
Method that allows base class to combine systems ///////////////.
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 1462 of file SystemTwo.cpp.
References ARB, and NA.
initializeBasis()
template<typename Scalar > void SystemTwo< Scalar >::initializeBasis override protected virtual
Method that allows base class to initialize Basis //////////////.
Restrict one atom states to the allowed quantum numbers ////////
Check whether the single atom states fit to the symmetries /////
Check which basis vectors contain artificial states ////////////
Build two atom states //////////////////////////////////////////
Combine one atom states ////////////////////////////////////////
Loop over user-defined states //////////////////////////////////
Build data /////////////////////////////////////////////////////
Remove vectors with too small norm /////////////////////////////
Remove states that barely occur ////////////////////////////////
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 202 of file SystemTwo.cpp.
References ARB, EVEN, StateOne::getJ(), StateOne::getL(), StateOne::getM(), StateOne::getReflected(), enumerated_state< T >::idx, NA, and ODD.
initializeInteraction()
template<typename Scalar > void SystemTwo< Scalar >::initializeInteraction override protected virtual
Method that allows base class to calculate the interaction /////.
Prepare the calculation of the interaction /////////////////////
Generate the interaction in the canonical basis ////////////////
Build and transform the interaction to the used basis //////////
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 656 of file SystemTwo.cpp.
References GreenTensor::addSurface(), coulombs_constant, GreenTensor::getDDTensor(), GreenTensor::getDQTensor(), GreenTensor::getQDTensor(), and selectionRulesMultipoleNew().
onStatesChange()
template<typename Scalar > void SystemTwo< Scalar >::onStatesChange override protected virtual
Methods that allows base class to communicate with subclass ////.
Reimplemented from SystemBase< Scalar_, StateTwo >.
Definition at line 1528 of file SystemTwo.cpp.
rotateStates()
template<typename Scalar > Eigen::SparseMatrix< Scalar > SystemTwo< Scalar >::rotateStates (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) override protected virtual
Methods that allows base class to rotate states ////////////////.
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 1408 of file SystemTwo.cpp.
setAngle()
template<typename Scalar > void SystemTwo< Scalar >::setAngle (double a)
Definition at line 130 of file SystemTwo.cpp.
Referenced by TEST_CASE_FIXTURE().
setConservedMomentaUnderRotation()
template<typename Scalar > void SystemTwo< Scalar >::setConservedMomentaUnderRotation (const std::set< int > & momenta)
Definition at line 170 of file SystemTwo.cpp.
References ARB.
setConservedParityUnderInversion()
template<typename Scalar > void SystemTwo< Scalar >::setConservedParityUnderInversion (parity_t parity)
Definition at line 150 of file SystemTwo.cpp.
setConservedParityUnderPermutation()
template<typename Scalar > void SystemTwo< Scalar >::setConservedParityUnderPermutation (parity_t parity)
Definition at line 144 of file SystemTwo.cpp.
Referenced by TEST_CASE_FIXTURE().
setConservedParityUnderReflection()
template<typename Scalar > void SystemTwo< Scalar >::setConservedParityUnderReflection (parity_t parity)
Definition at line 156 of file SystemTwo.cpp.
setDistance()
template<typename Scalar > void SystemTwo< Scalar >::setDistance (double d)
Definition at line 109 of file SystemTwo.cpp.
Referenced by TEST_CASE_FIXTURE().
setDistanceVector()
template<typename Scalar > void SystemTwo< Scalar >::setDistanceVector (std::array< double, 3 > d)
Definition at line 118 of file SystemTwo.cpp.
setOneAtomBasisvectors()
template<typename Scalar > void SystemTwo< Scalar >::setOneAtomBasisvectors (const std::vector< std::array< size_t, 2 >> & indices)
Definition at line 184 of file SystemTwo.cpp.
setOrder()
template<typename Scalar > void SystemTwo< Scalar >::setOrder (double o)
Definition at line 138 of file SystemTwo.cpp.
setSurfaceDistance()
template<typename Scalar > void SystemTwo< Scalar >::setSurfaceDistance (double d)
Definition at line 100 of file SystemTwo.cpp.
transformInteraction()
template<typename Scalar > void SystemTwo< Scalar >::transformInteraction (const Eigen::SparseMatrix< Scalar_ > & transformator) override protected virtual
Method that allows base class to transform the interaction /////.
Implements SystemBase< Scalar_, StateTwo >.
Definition at line 1371 of file SystemTwo.cpp.
Friends And Related Function Documentation
cereal::access
template<typename Scalar_ > friend class cereal::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 182 of file SystemTwo.hpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/SystemOne.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/SystemTwo.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/SystemTwo.cpp