pairinteraction: pairinteraction::BasisPairCreator< Scalar > Class Template Reference
pairinteraction::BasisPairCreator< Scalar > Class Template Reference
#include <BasisPairCreator.hpp>
Public Types
using real_t = typename traits::NumTraits< Scalar >::real_t
using basis_t = BasisPair< Scalar >
using ket_t = KetPair< Scalar >
using ketvec_t = std::vector< std::shared_ptr< const ket_t > >
Public Member Functions
BasisPairCreator ()
BasisPairCreator< Scalar > & add (const SystemAtom< Scalar > &system_atom)
BasisPairCreator< Scalar > & restrict_energy (real_t min, real_t max)
BasisPairCreator< Scalar > & restrict_quantum_number_m (real_t min, real_t max)
BasisPairCreator< Scalar > & restrict_product_of_parities (Parity value)
std::shared_ptr< const BasisPair< Scalar > > create () const
Detailed Description
template<typename Scalar>
class pairinteraction::BasisPairCreator< Scalar >
Definition at line 26 of file BasisPairCreator.hpp.
Member Typedef Documentation
basis_t
template<typename Scalar > using pairinteraction::BasisPairCreator< Scalar >::basis_t = BasisPair<Scalar>
Definition at line 31 of file BasisPairCreator.hpp.
ket_t
template<typename Scalar > using pairinteraction::BasisPairCreator< Scalar >::ket_t = KetPair<Scalar>
Definition at line 32 of file BasisPairCreator.hpp.
ketvec_t
template<typename Scalar > using pairinteraction::BasisPairCreator< Scalar >::ketvec_t = std::vector<std::shared_ptr<const ket_t> >
Definition at line 33 of file BasisPairCreator.hpp.
real_t
template<typename Scalar > using pairinteraction::BasisPairCreator< Scalar >::real_t = typename traits::NumTraits<Scalar>::real_t
Definition at line 30 of file BasisPairCreator.hpp.
Constructor & Destructor Documentation
BasisPairCreator()
template<typename Scalar > pairinteraction::BasisPairCreator< Scalar >::BasisPairCreator
Definition at line 20 of file BasisPairCreator.cpp.
References pairinteraction::UNKNOWN.
Member Function Documentation
add()
template<typename Scalar > BasisPairCreator< Scalar > & pairinteraction::BasisPairCreator< Scalar >::add (const SystemAtom< Scalar > & system_atom)
Definition at line 23 of file BasisPairCreator.cpp.
References pairinteraction::System< Derived >::is_diagonal().
Referenced by pairinteraction::DOCTEST_TEST_CASE(), pairinteraction::BasisPair< Scalar >::get_matrix_elements(), and main().
create()
template<typename Scalar > std::shared_ptr< const BasisPair< Scalar > > pairinteraction::BasisPairCreator< Scalar >::create
Definition at line 51 of file BasisPairCreator.cpp.
References pairinteraction::UNKNOWN.
restrict_energy()
template<typename Scalar > BasisPairCreator< Scalar > & pairinteraction::BasisPairCreator< Scalar >::restrict_energy (real_t min, real_t max)
Definition at line 32 of file BasisPairCreator.cpp.
restrict_product_of_parities()
template<typename Scalar > BasisPairCreator< Scalar > & pairinteraction::BasisPairCreator< Scalar >::restrict_product_of_parities (Parity value)
Definition at line 45 of file BasisPairCreator.cpp.
restrict_quantum_number_m()
template<typename Scalar > BasisPairCreator< Scalar > & pairinteraction::BasisPairCreator< Scalar >::restrict_quantum_number_m (real_t min, real_t max)
Definition at line 38 of file BasisPairCreator.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/basis/BasisPair.hpp
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/basis/BasisPairCreator.hpp
/__w/pairinteraction/pairinteraction/src/cpp/src/basis/BasisPairCreator.cpp