pairinteraction: sqlite::statement Class Reference
sqlite::statement Class Reference
SQLite Statement handle.
#include <SQLite.hpp>
Data Structures
class iterator
Statement iterator.
Public Member Functions
statement (sqlite3 *db)
Constructor.
statement (sqlite3 *db, std::string sql)
Constructor.
void set (std::string const &sql)
Set the query string.
void set (std::stringstream const &ss)
void prepare ()
Prepare the statement.
bool step ()
Step the statement.
void reset ()
Reset the statement.
void exec (std::string const &sql)
Execute SQLite statements.
void bind (int where, std::string const &s)
Bind a value to a position in the query.
void bind (int where, std::string &&s)
void bind (int where, double d)
void bind (int where, int i)
template<typename ReturnType >
ReturnType get (int field)
Get value of a field.
iterator begin ()
returns an iterator to the beginning
iterator end ()
returns an empty iterator
Detailed Description
SQLite Statement handle.
This object wraps an SQLite statement. It is iterable in a while loop with the step() function or in a range-based for loop.
Definition at line 77 of file SQLite.hpp.
Constructor & Destructor Documentation
statement() [1/2]
sqlite::statement::statement (sqlite3 * db) inline explicit
Constructor.
This is called in the query function of the the handle object.
Parameters
[in] db unmanaged raw pointer to the sqlite database
Definition at line 97 of file SQLite.hpp.
statement() [2/2]
sqlite::statement::statement (sqlite3 * db, std::string sql) inline explicit
Constructor.
This is called in the query function of the the handle object. This variant also sets a default query.
Parameters
[in] db unmanaged raw pointer to the sqlite database
[in] sql an initial query as a string
Definition at line 107 of file SQLite.hpp.
Member Function Documentation
begin()
iterator sqlite::statement::begin () inline
returns an iterator to the beginning
With this, a statement can be iterated in a C++11 range-based for loop.
Warning
This is not zero overhead! If you care about performance use a while loop using step() instead.
while(stmt.step())
    stmt.get<...>(...);
Returns
iterator to the beginning
Definition at line 301 of file SQLite.hpp.
bind() [1/4]
void sqlite::statement::bind (int where, double d) inline
Definition at line 214 of file SQLite.hpp.
bind() [2/4]
void sqlite::statement::bind (int where, int i) inline
Definition at line 217 of file SQLite.hpp.
bind() [3/4]
void sqlite::statement::bind (int where, std::string && s) inline
Definition at line 208 of file SQLite.hpp.
bind() [4/4]
void sqlite::statement::bind (int where, std::string const & s) inline
Bind a value to a position in the query.
Parameters
[in] where position in the query (one-based)
[in] s string to bind
Exceptions
sqlite::error This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 203 of file SQLite.hpp.
Referenced by TEST_CASE().
end()
iterator sqlite::statement::end () inline
returns an empty iterator
The iterator for the SQLite statement is a forward iterator which is implemented in terms of the step() function. Since the step() function will determine the end by itself, this iterator is merely a sentinel.
Returns
empty iterator
Definition at line 312 of file SQLite.hpp.
Referenced by TEST_CASE().
exec()
void sqlite::statement::exec (std::string const & sql) inline
Execute SQLite statements.
The SQL statements are passed to this function as a string and are executed in-place.
Parameters
[in] sql SQL statements
Exceptions
sqlite::error
Definition at line 191 of file SQLite.hpp.
Referenced by HamiltonianOne< Scalar >::build(), HamiltonianTwo< Scalar >::calculate(), QuantumDefect::QuantumDefect(), and TEST_CASE().
get()
template<typename ReturnType > ReturnType sqlite::statement::get (int field)
Get value of a field.
Retrieve the value stored at position field as datatype ReturnType.
Template Parameters
ReturnType requested return type
Parameters
[in] field
Returns
the value stored in field as datatype ReturnType
Referenced by HamiltonianOne< Scalar >::build(), HamiltonianTwo< Scalar >::calculate(), and TEST_CASE().
prepare()
void sqlite::statement::prepare () inline
Prepare the statement.
Prepare the statement for stepping.
Exceptions
sqlite::error
Definition at line 130 of file SQLite.hpp.
Referenced by HamiltonianOne< Scalar >::build(), HamiltonianTwo< Scalar >::calculate(), and TEST_CASE().
reset()
void sqlite::statement::reset () inline
Reset the statement.
Reset the statement so you can rebind values.
Exceptions
sqlite::error
Definition at line 178 of file SQLite.hpp.
Referenced by TEST_CASE().
set() [1/2]
void sqlite::statement::set (std::string const & sql) inline
Set the query string.
Parameters
[in] sql the query string
Exceptions
sqlite::error This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 116 of file SQLite.hpp.
Referenced by TEST_CASE().
set() [2/2]
void sqlite::statement::set (std::stringstream const & ss) inline
Definition at line 122 of file SQLite.hpp.
References set().
Referenced by set().
step()
bool sqlite::statement::step () inline
Step the statement.
This steps the statement.
Returns
true if there is a row, false otherwise
Exceptions
sqlite::error
Definition at line 148 of file SQLite.hpp.
Referenced by HamiltonianOne< Scalar >::build(), HamiltonianTwo< Scalar >::calculate(), sqlite::statement::iterator::iterator(), sqlite::statement::iterator::operator++(), and TEST_CASE().
The documentation for this class was generated from the following file:
/__w/pairinteraction/pairinteraction/pairinteraction/SQLite.hpp