pairinteraction: Hamiltonianmatrix< Scalar > Class Template Reference
Hamiltonianmatrix< Scalar > Class Template Reference
#include <Hamiltonianmatrix.hpp>
Public Member Functions
Hamiltonianmatrix ()
Hamiltonianmatrix (const Eigen::SparseMatrix< Scalar > &entries, const Eigen::SparseMatrix< Scalar > &basis)
Hamiltonianmatrix (size_t szBasis, size_t szEntries)
Eigen::SparseMatrix< Scalar > & entries ()
const Eigen::SparseMatrix< Scalar > & entries () const
Eigen::SparseMatrix< Scalar > & basis ()
const Eigen::SparseMatrix< Scalar > & basis () const
size_t num_basisvectors () const
size_t num_coordinates () const
void addBasis (idx_t row, idx_t col, Scalar val)
void addEntries (idx_t row, idx_t col, Scalar val)
void compress (size_t nBasis, size_t nCoordinates)
std::vector< Hamiltonianmatrix > findSubs () const
Hamiltonianmatrix abs () const
Hamiltonianmatrix changeBasis (const Eigen::SparseMatrix< Scalar > &basis) const
void applyCutoff (double cutoff)
void findUnnecessaryStates (std::vector< bool > &isNecessaryCoordinate) const
void removeUnnecessaryBasisvectors (const std::vector< bool > &isNecessaryCoordinate)
void removeUnnecessaryBasisvectors ()
void removeUnnecessaryStates (const std::vector< bool > &isNecessaryCoordinate)
Hamiltonianmatrix getBlock (const std::vector< ptrdiff_t > &indices)
void diagonalize ()
Hamiltonianmatrix & operator+= (const Hamiltonianmatrix &rhs)
Hamiltonianmatrix & operator-= (const Hamiltonianmatrix &rhs)
bytes_t & serialize () override
void doSerialization ()
void deserialize (bytes_t &bytesin) override
void doDeserialization ()
uint64_t hashEntries ()
uint64_t hashBasis ()
void save (const std::string &fname)
bool load (const std::string &fname)
template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr>
void mergeComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr>
void mergeComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr>
void splitComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr>
void splitComplex (std::vector< storage_double > &real, std::vector< storage_double > &imag, std::vector< T > &complex)
Public Member Functions inherited from Serializable
virtual ~Serializable ()=default
Protected Attributes
Eigen::SparseMatrix< Scalar > entries_
Eigen::SparseMatrix< Scalar > basis_
bytes_t bytes
std::vector< Eigen::Triplet< Scalar > > triplets_basis
std::vector< Eigen::Triplet< Scalar > > triplets_entries
Friends
Hamiltonianmatrix operator+ (Hamiltonianmatrix lhs, const Hamiltonianmatrix &rhs)
Hamiltonianmatrix operator- (Hamiltonianmatrix lhs, const Hamiltonianmatrix &rhs)
template<typename S , typename T >
Hamiltonianmatrix< S > operator* (const T &lhs, Hamiltonianmatrix< S > rhs)
template<typename S , typename T >
Hamiltonianmatrix< S > operator* (Hamiltonianmatrix< S > lhs, const T &rhs)
Hamiltonianmatrix combine (const Hamiltonianmatrix &lhs, const Hamiltonianmatrix &rhs, const double &deltaE, const std::shared_ptr< BasisnamesTwo > &basis_two, const Symmetry &sym)
void energycutoff (const Hamiltonianmatrix &lhs, const Hamiltonianmatrix &rhs, const double &deltaE, std::vector< bool > &necessary)
Detailed Description
template<typename Scalar>
class Hamiltonianmatrix< Scalar >
Definition at line 68 of file Hamiltonianmatrix.hpp.
Constructor & Destructor Documentation
Hamiltonianmatrix() [1/3]
template<typename Scalar > Hamiltonianmatrix< Scalar >::Hamiltonianmatrix () default
Hamiltonianmatrix() [2/3]
template<typename Scalar > Hamiltonianmatrix< Scalar >::Hamiltonianmatrix (const Eigen::SparseMatrix< Scalar > & entries, const Eigen::SparseMatrix< Scalar > & basis)
Definition at line 33 of file Hamiltonianmatrix.cpp.
Hamiltonianmatrix() [3/3]
template<typename Scalar > Hamiltonianmatrix< Scalar >::Hamiltonianmatrix (size_t szBasis, size_t szEntries)
Definition at line 38 of file Hamiltonianmatrix.cpp.
Member Function Documentation
abs()
template<typename Scalar > Hamiltonianmatrix< Scalar > Hamiltonianmatrix< Scalar >::abs
Definition at line 103 of file Hamiltonianmatrix.cpp.
addBasis()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::addBasis (idx_t row, idx_t col, Scalar val)
Definition at line 76 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build().
addEntries()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::addEntries (idx_t row, idx_t col, Scalar val)
Definition at line 81 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build().
applyCutoff()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::applyCutoff (double cutoff)
Definition at line 116 of file Hamiltonianmatrix.cpp.
basis() [1/2]
template<typename Scalar > Eigen::SparseMatrix< Scalar > & Hamiltonianmatrix< Scalar >::basis
Definition at line 55 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianTwo< Scalar >::calculate().
basis() [2/2]
template<typename Scalar > const Eigen::SparseMatrix< Scalar > & Hamiltonianmatrix< Scalar >::basis
Definition at line 61 of file Hamiltonianmatrix.cpp.
changeBasis()
template<typename Scalar > Hamiltonianmatrix< Scalar > Hamiltonianmatrix< Scalar >::changeBasis (const Eigen::SparseMatrix< Scalar > & basis) const
Definition at line 109 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianTwo< Scalar >::calculate().
compress()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::compress (size_t nBasis, size_t nCoordinates)
Definition at line 86 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build().
deserialize()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::deserialize (bytes_t & bytesin) override virtual
Implements Serializable.
Definition at line 408 of file Hamiltonianmatrix.cpp.
diagonalize()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::diagonalize
Definition at line 267 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build(), and HamiltonianTwo< Scalar >::calculate().
doDeserialization()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::doDeserialization
Definition at line 414 of file Hamiltonianmatrix.cpp.
References complex_not_real, numpy::copy, and Serializer::load().
doSerialization()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::doSerialization
Definition at line 341 of file Hamiltonianmatrix.cpp.
References complex_not_real, csr_not_csc, and Serializer::save().
entries() [1/2]
template<typename Scalar > Eigen::SparseMatrix< Scalar > & Hamiltonianmatrix< Scalar >::entries
Definition at line 44 of file Hamiltonianmatrix.cpp.
entries() [2/2]
template<typename Scalar > const Eigen::SparseMatrix< Scalar > & Hamiltonianmatrix< Scalar >::entries
Definition at line 50 of file Hamiltonianmatrix.cpp.
findSubs()
template<typename Scalar > std::vector< Hamiltonianmatrix< Scalar > > Hamiltonianmatrix< Scalar >::findSubs
Definition at line 96 of file Hamiltonianmatrix.cpp.
findUnnecessaryStates()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::findUnnecessaryStates (std::vector< bool > & isNecessaryCoordinate) const
Definition at line 141 of file Hamiltonianmatrix.cpp.
getBlock()
template<typename Scalar > Hamiltonianmatrix< Scalar > Hamiltonianmatrix< Scalar >::getBlock (const std::vector< ptrdiff_t > & indices)
Definition at line 251 of file Hamiltonianmatrix.cpp.
hashBasis()
template<typename Scalar > uint64_t Hamiltonianmatrix< Scalar >::hashBasis
Definition at line 487 of file Hamiltonianmatrix.cpp.
References utils::FNV64().
hashEntries()
template<typename Scalar > uint64_t Hamiltonianmatrix< Scalar >::hashEntries
Definition at line 480 of file Hamiltonianmatrix.cpp.
References utils::FNV64().
load()
template<typename Scalar > bool Hamiltonianmatrix< Scalar >::load (const std::string & fname)
Definition at line 509 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build(), and HamiltonianTwo< Scalar >::calculate().
mergeComplex() [1/2]
template<typename Scalar > template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix< Scalar >::mergeComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 117 of file Hamiltonianmatrix.hpp.
mergeComplex() [2/2]
template<typename Scalar > template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix< Scalar >::mergeComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 128 of file Hamiltonianmatrix.hpp.
num_basisvectors()
template<typename Scalar > size_t Hamiltonianmatrix< Scalar >::num_basisvectors
Definition at line 66 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build(), and HamiltonianTwo< Scalar >::calculate().
num_coordinates()
template<typename Scalar > size_t Hamiltonianmatrix< Scalar >::num_coordinates
Definition at line 71 of file Hamiltonianmatrix.cpp.
operator+=()
template<typename Scalar > Hamiltonianmatrix< Scalar > & Hamiltonianmatrix< Scalar >::operator+= (const Hamiltonianmatrix< Scalar > & rhs)
Definition at line 320 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix< Scalar >::entries_.
operator-=()
template<typename Scalar > Hamiltonianmatrix< Scalar > & Hamiltonianmatrix< Scalar >::operator-= (const Hamiltonianmatrix< Scalar > & rhs)
Definition at line 328 of file Hamiltonianmatrix.cpp.
References Hamiltonianmatrix< Scalar >::entries_.
removeUnnecessaryBasisvectors() [1/2]
template<typename Scalar > void Hamiltonianmatrix< Scalar >::removeUnnecessaryBasisvectors
Definition at line 195 of file Hamiltonianmatrix.cpp.
removeUnnecessaryBasisvectors() [2/2]
template<typename Scalar > void Hamiltonianmatrix< Scalar >::removeUnnecessaryBasisvectors (const std::vector< bool > & isNecessaryCoordinate)
Definition at line 159 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianTwo< Scalar >::calculate().
removeUnnecessaryStates()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::removeUnnecessaryStates (const std::vector< bool > & isNecessaryCoordinate)
Definition at line 227 of file Hamiltonianmatrix.cpp.
save()
template<typename Scalar > void Hamiltonianmatrix< Scalar >::save (const std::string & fname)
Definition at line 494 of file Hamiltonianmatrix.cpp.
Referenced by HamiltonianOne< Scalar >::build(), and HamiltonianTwo< Scalar >::calculate().
serialize()
template<typename Scalar > bytes_t & Hamiltonianmatrix< Scalar >::serialize override virtual
Implements Serializable.
Definition at line 335 of file Hamiltonianmatrix.cpp.
splitComplex() [1/2]
template<typename Scalar > template<typename T , typename std::enable_if< utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix< Scalar >::splitComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 135 of file Hamiltonianmatrix.hpp.
splitComplex() [2/2]
template<typename Scalar > template<typename T , typename std::enable_if<!utils::is_complex< T >::value >::type * = nullptr> void Hamiltonianmatrix< Scalar >::splitComplex (std::vector< storage_double > & real, std::vector< storage_double > & imag, std::vector< T > & complex) inline
Definition at line 146 of file Hamiltonianmatrix.hpp.
Friends And Related Function Documentation
combine
template<typename Scalar > Hamiltonianmatrix combine (const Hamiltonianmatrix< Scalar > & lhs, const Hamiltonianmatrix< Scalar > & rhs, const double & deltaE, const std::shared_ptr< BasisnamesTwo > & basis_two, const Symmetry & sym) friend
Definition at line 542 of file Hamiltonianmatrix.cpp.
energycutoff
template<typename Scalar > void energycutoff (const Hamiltonianmatrix< Scalar > & lhs, const Hamiltonianmatrix< Scalar > & rhs, const double & deltaE, std::vector< bool > & necessary) friend
Definition at line 778 of file Hamiltonianmatrix.cpp.
operator* [1/2]
template<typename Scalar > template<typename S , typename T > Hamiltonianmatrix<S> operator* (const T & lhs, Hamiltonianmatrix< S > rhs) friend
operator* [2/2]
template<typename Scalar > template<typename S , typename T > Hamiltonianmatrix<S> operator* (Hamiltonianmatrix< S > lhs, const T & rhs) friend
operator+
template<typename Scalar > Hamiltonianmatrix operator+ (Hamiltonianmatrix< Scalar > lhs, const Hamiltonianmatrix< Scalar > & rhs) friend
Definition at line 289 of file Hamiltonianmatrix.cpp.
operator-
template<typename Scalar > Hamiltonianmatrix operator- (Hamiltonianmatrix< Scalar > lhs, const Hamiltonianmatrix< Scalar > & rhs) friend
Definition at line 297 of file Hamiltonianmatrix.cpp.
Field Documentation
basis_
template<typename Scalar > Eigen::SparseMatrix<Scalar> Hamiltonianmatrix< Scalar >::basis_ protected
Definition at line 154 of file Hamiltonianmatrix.hpp.
bytes
template<typename Scalar > bytes_t Hamiltonianmatrix< Scalar >::bytes protected
Definition at line 155 of file Hamiltonianmatrix.hpp.
Referenced by operator*().
entries_
template<typename Scalar > Eigen::SparseMatrix<Scalar> Hamiltonianmatrix< Scalar >::entries_ protected
Definition at line 153 of file Hamiltonianmatrix.hpp.
Referenced by operator*(), Hamiltonianmatrix< Scalar >::operator+=(), and Hamiltonianmatrix< Scalar >::operator-=().
triplets_basis
template<typename Scalar > std::vector<Eigen::Triplet<Scalar> > Hamiltonianmatrix< Scalar >::triplets_basis protected
Definition at line 156 of file Hamiltonianmatrix.hpp.
triplets_entries
template<typename Scalar > std::vector<Eigen::Triplet<Scalar> > Hamiltonianmatrix< Scalar >::triplets_entries protected
Definition at line 157 of file Hamiltonianmatrix.hpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/Hamiltonianmatrix.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/Hamiltonianmatrix.cpp