pairinteraction: pairinteraction::Basis< Derived > Class Template Reference
pairinteraction::Basis< Derived > Class Template Reference abstract
Base class for a basis.
#include <Basis.hpp>
Data Structures
class Iterator
Public Types
using scalar_t = typename traits::CrtpTraits< Derived >::scalar_t
using real_t = typename traits::CrtpTraits< Derived >::real_t
using ket_t = typename traits::CrtpTraits< Derived >::ket_t
using ketvec_t = typename traits::CrtpTraits< Derived >::ketvec_t
Public Types inherited from pairinteraction::TransformationBuilderInterface< traits::CrtpTraits< Derived >::scalar_t >
using real_t = typename traits::NumTraits< traits::CrtpTraits< Derived >::scalar_t >::real_t
Public Member Functions
Basis ()=delete
virtual ~Basis ()=default
bool has_quantum_number_f () const
bool has_quantum_number_m () const
bool has_parity () const
const ketvec_t & get_kets () const
size_t get_number_of_states () const
size_t get_number_of_kets () const
real_t get_quantum_number_f (size_t state_index) const
real_t get_quantum_number_m (size_t state_index) const
Parity get_parity (size_t state_index) const
std::shared_ptr< const Derived > get_state (size_t state_index) const
std::shared_ptr< const ket_t > get_ket (size_t ket_index) const
std::shared_ptr< const ket_t > get_corresponding_ket (size_t state_index) const
std::shared_ptr< const ket_t > get_corresponding_ket (std::shared_ptr< const Derived > state) const
size_t get_corresponding_ket_index (size_t state_index) const
size_t get_corresponding_ket_index (std::shared_ptr< const Derived > state) const
std::shared_ptr< const Derived > get_corresponding_state (size_t ket_index) const
std::shared_ptr< const Derived > get_corresponding_state (std::shared_ptr< const ket_t > ket) const
size_t get_corresponding_state_index (size_t ket_index) const
size_t get_corresponding_state_index (std::shared_ptr< const ket_t > ket) const
std::shared_ptr< const Derived > get_canonical_state_from_ket (size_t ket_index) const
std::shared_ptr< const Derived > get_canonical_state_from_ket (std::shared_ptr< const ket_t > ket) const
const Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > & get_coefficients () const
Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > & get_coefficients ()
void set_coefficients (const Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > &values)
Eigen::VectorX< scalar_t > get_amplitudes (std::shared_ptr< const ket_t > ket) const
Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > get_amplitudes (std::shared_ptr< const Derived > other) const
Eigen::VectorX< real_t > get_overlaps (std::shared_ptr< const ket_t > ket) const
Eigen::SparseMatrix< real_t, Eigen::RowMajor > get_overlaps (std::shared_ptr< const Derived > other) const
virtual Eigen::VectorX< scalar_t > get_matrix_elements (std::shared_ptr< const ket_t > ket, OperatorType type, int q=0) const =0
virtual Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > get_matrix_elements (std::shared_ptr< const Derived > other, OperatorType type, int q=0) const =0
Iterator begin () const
Iterator end () const
const Transformation< scalar_t > & get_transformation () const override
Transformation< scalar_t > get_rotator (real_t alpha, real_t beta, real_t gamma) const override
Sorting get_sorter (const std::vector< TransformationType > &labels) const override
std::vector< IndicesOfBlock > get_indices_of_blocks (const std::vector< TransformationType > &labels) const override
void perform_sorter_checks (const std::vector< TransformationType > &labels) const
void perform_blocks_checks (const std::set< TransformationType > &unique_labels) const
void get_sorter_without_checks (const std::vector< TransformationType > &labels, Sorting &transformation) const
void get_indices_of_blocks_without_checks (const std::set< TransformationType > &unique_labels, IndicesOfBlocksCreator &blocks) const
std::shared_ptr< const Derived > transformed (const Transformation< scalar_t > &transformation) const
std::shared_ptr< const Derived > transformed (const Sorting &transformation) const
Public Member Functions inherited from pairinteraction::TransformationBuilderInterface< traits::CrtpTraits< Derived >::scalar_t >
virtual ~TransformationBuilderInterface ()=default
virtual const Transformation< traits::CrtpTraits< Derived >::scalar_t > & get_transformation () const=0
virtual Transformation< traits::CrtpTraits< Derived >::scalar_t > get_rotator (real_t alpha, real_t beta, real_t gamma) const=0
Transformation< traits::CrtpTraits< Derived >::scalar_t > get_rotator (const std::array< real_t, 3 > &to_z_axis, const std::array< real_t, 3 > &to_y_axis) const
virtual Sorting get_sorter (const std::vector< TransformationType > &labels) const=0
virtual std::vector< IndicesOfBlock > get_indices_of_blocks (const std::vector< TransformationType > &labels) const=0
Protected Member Functions
Basis (ketvec_t &&kets)
int get_ket_index_from_ket (std::shared_ptr< const ket_t > ket) const
Protected Attributes
ketvec_t kets
Detailed Description
template<typename Derived>
class pairinteraction::Basis< Derived >
Base class for a basis.
This base class represents a basis. It comprises a list of ket states and a matrix of coefficients. The rows of the coefficient matrix correspond to indices of ket states and the columns to indices of basis vectors. Using CRPT, it is a base class for specific basis implementations. Its constructor is protected to indicate that derived classes should not allow direct instantiation. Instead, a factory class should be provided that is a friend of the derived class and can create instances of it.
Template Parameters
Derived Derived class.
Definition at line 40 of file Basis.hpp.
Member Typedef Documentation
ket_t
template<typename Derived > using pairinteraction::Basis< Derived >::ket_t = typename traits::CrtpTraits<Derived>::ket_t
Definition at line 45 of file Basis.hpp.
ketvec_t
template<typename Derived > using pairinteraction::Basis< Derived >::ketvec_t = typename traits::CrtpTraits<Derived>::ketvec_t
Definition at line 46 of file Basis.hpp.
real_t
template<typename Derived > using pairinteraction::Basis< Derived >::real_t = typename traits::CrtpTraits<Derived>::real_t
Definition at line 44 of file Basis.hpp.
scalar_t
template<typename Derived > using pairinteraction::Basis< Derived >::scalar_t = typename traits::CrtpTraits<Derived>::scalar_t
Definition at line 43 of file Basis.hpp.
Constructor & Destructor Documentation
Basis() [1/2]
template<typename Derived > pairinteraction::Basis< Derived >::Basis () delete
~Basis()
template<typename Derived > virtual pairinteraction::Basis< Derived >::~Basis () virtual default
Basis() [2/2]
template<typename Derived > pairinteraction::Basis< Derived >::Basis (ketvec_t && kets) protected
Definition at line 59 of file Basis.cpp.
Member Function Documentation
begin()
template<typename Derived > Basis< Derived >::Iterator pairinteraction::Basis< Derived >::begin
Definition at line 361 of file Basis.cpp.
References pairinteraction::Basis< Derived >::begin().
Referenced by pairinteraction::Basis< Derived >::begin().
end()
template<typename Derived > Basis< Derived >::Iterator pairinteraction::Basis< Derived >::end
Definition at line 366 of file Basis.cpp.
References pairinteraction::Basis< Derived >::end().
Referenced by pairinteraction::Basis< Derived >::end().
get_amplitudes() [1/2]
template<typename Derived > Eigen::SparseMatrix< typename Basis< Derived >::scalar_t, Eigen::RowMajor > pairinteraction::Basis< Derived >::get_amplitudes (std::shared_ptr< const Derived > other) const
Definition at line 178 of file Basis.cpp.
References pairinteraction::Transformation< Scalar >::matrix.
get_amplitudes() [2/2]
template<typename Derived > Eigen::VectorX< typename Basis< Derived >::scalar_t > pairinteraction::Basis< Derived >::get_amplitudes (std::shared_ptr< const ket_t > ket) const
Definition at line 166 of file Basis.cpp.
get_canonical_state_from_ket() [1/2]
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::get_canonical_state_from_ket (size_t ket_index) const
Definition at line 322 of file Basis.cpp.
Referenced by pairinteraction::BasisPair< Scalar >::get_matrix_elements().
get_canonical_state_from_ket() [2/2]
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::get_canonical_state_from_ket (std::shared_ptr< const ket_t > ket) const
Definition at line 352 of file Basis.cpp.
get_coefficients() [1/2]
template<typename Derived > Eigen::SparseMatrix< typename Basis< Derived >::scalar_t, Eigen::RowMajor > & pairinteraction::Basis< Derived >::get_coefficients
Definition at line 126 of file Basis.cpp.
get_coefficients() [2/2]
template<typename Derived > const Eigen::SparseMatrix< typename Basis< Derived >::scalar_t, Eigen::RowMajor > & pairinteraction::Basis< Derived >::get_coefficients
Definition at line 120 of file Basis.cpp.
get_corresponding_ket() [1/2]
template<typename Derived > std::shared_ptr< const typename Basis< Derived >::ket_t > pairinteraction::Basis< Derived >::get_corresponding_ket (size_t state_index) const
Definition at line 223 of file Basis.cpp.
get_corresponding_ket() [2/2]
template<typename Derived > std::shared_ptr< const typename Basis< Derived >::ket_t > pairinteraction::Basis< Derived >::get_corresponding_ket (std::shared_ptr< const Derived > state) const
Definition at line 233 of file Basis.cpp.
get_corresponding_ket_index() [1/2]
template<typename Derived > size_t pairinteraction::Basis< Derived >::get_corresponding_ket_index (size_t state_index) const
Definition at line 307 of file Basis.cpp.
get_corresponding_ket_index() [2/2]
template<typename Derived > size_t pairinteraction::Basis< Derived >::get_corresponding_ket_index (std::shared_ptr< const Derived > state) const
Definition at line 316 of file Basis.cpp.
get_corresponding_state() [1/2]
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::get_corresponding_state (size_t ket_index) const
Definition at line 270 of file Basis.cpp.
get_corresponding_state() [2/2]
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::get_corresponding_state (std::shared_ptr< const ket_t > ket) const
Definition at line 280 of file Basis.cpp.
get_corresponding_state_index() [1/2]
template<typename Derived > size_t pairinteraction::Basis< Derived >::get_corresponding_state_index (size_t ket_index) const
Definition at line 289 of file Basis.cpp.
get_corresponding_state_index() [2/2]
template<typename Derived > size_t pairinteraction::Basis< Derived >::get_corresponding_state_index (std::shared_ptr< const ket_t > ket) const
Definition at line 298 of file Basis.cpp.
get_indices_of_blocks()
template<typename Derived > std::vector< IndicesOfBlock > pairinteraction::Basis< Derived >::get_indices_of_blocks (const std::vector< TransformationType > & labels) const override virtual
Implements pairinteraction::TransformationBuilderInterface< traits::CrtpTraits< Derived >::scalar_t >.
Definition at line 466 of file Basis.cpp.
References pairinteraction::Basis< Derived >::get_indices_of_blocks_without_checks(), pairinteraction::Transformation< Scalar >::matrix, pairinteraction::Basis< Derived >::perform_blocks_checks(), and pairinteraction::Basis< Derived >::perform_sorter_checks().
get_indices_of_blocks_without_checks()
template<typename Derived > void pairinteraction::Basis< Derived >::get_indices_of_blocks_without_checks (const std::set< TransformationType > & unique_labels, IndicesOfBlocksCreator & blocks) const
Definition at line 561 of file Basis.cpp.
References pairinteraction::IndicesOfBlocksCreator::add(), pairinteraction::Transformation< Scalar >::matrix, pairinteraction::SORT_BY_KET, pairinteraction::SORT_BY_PARITY, pairinteraction::SORT_BY_QUANTUM_NUMBER_F, and pairinteraction::SORT_BY_QUANTUM_NUMBER_M.
Referenced by pairinteraction::Basis< Derived >::get_indices_of_blocks().
get_ket()
template<typename Derived > std::shared_ptr< const typename Basis< Derived >::ket_t > pairinteraction::Basis< Derived >::get_ket (size_t ket_index) const
Definition at line 265 of file Basis.cpp.
get_ket_index_from_ket()
template<typename Derived > int pairinteraction::Basis< Derived >::get_ket_index_from_ket (std::shared_ptr< const ket_t > ket) const protected
Definition at line 157 of file Basis.cpp.
Referenced by pairinteraction::Basis< Derived >::get_rotator().
get_kets()
template<typename Derived > const Basis< Derived >::ketvec_t & pairinteraction::Basis< Derived >::get_kets
Definition at line 114 of file Basis.cpp.
get_matrix_elements() [1/2]
template<typename Derived > virtual Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > pairinteraction::Basis< Derived >::get_matrix_elements (std::shared_ptr< const Derived > other, OperatorType type, int q = 0) const pure virtual
Implemented in pairinteraction::BasisAtom< Scalar >, and pairinteraction::BasisPair< Scalar >.
get_matrix_elements() [2/2]
template<typename Derived > virtual Eigen::VectorX< scalar_t > pairinteraction::Basis< Derived >::get_matrix_elements (std::shared_ptr< const ket_t > ket, OperatorType type, int q = 0) const pure virtual
Implemented in pairinteraction::BasisAtom< Scalar >, and pairinteraction::BasisPair< Scalar >.
get_number_of_kets()
template<typename Derived > size_t pairinteraction::Basis< Derived >::get_number_of_kets
Definition at line 395 of file Basis.cpp.
References pairinteraction::Transformation< Scalar >::matrix.
get_number_of_states()
template<typename Derived > size_t pairinteraction::Basis< Derived >::get_number_of_states
Definition at line 390 of file Basis.cpp.
References pairinteraction::Transformation< Scalar >::matrix.
get_overlaps() [1/2]
template<typename Derived > Eigen::SparseMatrix< typename Basis< Derived >::real_t, Eigen::RowMajor > pairinteraction::Basis< Derived >::get_overlaps (std::shared_ptr< const Derived > other) const
Definition at line 190 of file Basis.cpp.
get_overlaps() [2/2]
template<typename Derived > Eigen::VectorX< typename Basis< Derived >::real_t > pairinteraction::Basis< Derived >::get_overlaps (std::shared_ptr< const ket_t > ket) const
Definition at line 184 of file Basis.cpp.
get_parity()
template<typename Derived > Parity pairinteraction::Basis< Derived >::get_parity (size_t state_index) const
Definition at line 213 of file Basis.cpp.
get_quantum_number_f()
template<typename Derived > Basis< Derived >::real_t pairinteraction::Basis< Derived >::get_quantum_number_f (size_t state_index) const
Definition at line 195 of file Basis.cpp.
get_quantum_number_m()
template<typename Derived > Basis< Derived >::real_t pairinteraction::Basis< Derived >::get_quantum_number_m (size_t state_index) const
Definition at line 204 of file Basis.cpp.
get_rotator()
template<typename Derived > Transformation< typename Basis< Derived >::scalar_t > pairinteraction::Basis< Derived >::get_rotator (real_t alpha, real_t beta, real_t gamma) const override
Definition at line 407 of file Basis.cpp.
References pairinteraction::Basis< Derived >::get_ket_index_from_ket(), pairinteraction::Basis< Derived >::kets, pairinteraction::Transformation< Scalar >::matrix, and pairinteraction::ROTATE.
get_sorter()
template<typename Derived > Sorting pairinteraction::Basis< Derived >::get_sorter (const std::vector< TransformationType > & labels) const override virtual
Implements pairinteraction::TransformationBuilderInterface< traits::CrtpTraits< Derived >::scalar_t >.
Definition at line 438 of file Basis.cpp.
References pairinteraction::Basis< Derived >::get_sorter_without_checks(), pairinteraction::Transformation< Scalar >::matrix, pairinteraction::Sorting::matrix, pairinteraction::Basis< Derived >::perform_sorter_checks(), pairinteraction::SORT_BY_ENERGY, and pairinteraction::Sorting::transformation_type.
get_sorter_without_checks()
template<typename Derived > void pairinteraction::Basis< Derived >::get_sorter_without_checks (const std::vector< TransformationType > & labels, Sorting & transformation) const
Definition at line 480 of file Basis.cpp.
References pairinteraction::Transformation< Scalar >::matrix, pairinteraction::Sorting::matrix, pairinteraction::SORT_BY_KET, pairinteraction::SORT_BY_PARITY, pairinteraction::SORT_BY_QUANTUM_NUMBER_F, pairinteraction::SORT_BY_QUANTUM_NUMBER_M, pairinteraction::Sorting::transformation_type, and pairinteraction::UNKNOWN.
Referenced by pairinteraction::Basis< Derived >::get_sorter().
get_state()
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::get_state (size_t state_index) const
Definition at line 238 of file Basis.cpp.
get_transformation()
template<typename Derived > const Transformation< typename Basis< Derived >::scalar_t > & pairinteraction::Basis< Derived >::get_transformation override virtual
Implements pairinteraction::TransformationBuilderInterface< traits::CrtpTraits< Derived >::scalar_t >.
Definition at line 401 of file Basis.cpp.
has_parity()
template<typename Derived > bool pairinteraction::Basis< Derived >::has_parity
Definition at line 104 of file Basis.cpp.
has_quantum_number_f()
template<typename Derived > bool pairinteraction::Basis< Derived >::has_quantum_number_f
Definition at line 94 of file Basis.cpp.
has_quantum_number_m()
template<typename Derived > bool pairinteraction::Basis< Derived >::has_quantum_number_m
Definition at line 99 of file Basis.cpp.
perform_blocks_checks()
template<typename Derived > void pairinteraction::Basis< Derived >::perform_blocks_checks (const std::set< TransformationType > & unique_labels) const
Definition at line 36 of file Basis.cpp.
References pairinteraction::utils::is_sorting().
Referenced by pairinteraction::Basis< Derived >::get_indices_of_blocks().
perform_sorter_checks()
template<typename Derived > void pairinteraction::Basis< Derived >::perform_sorter_checks (const std::vector< TransformationType > & labels) const
Definition at line 26 of file Basis.cpp.
References pairinteraction::utils::is_sorting().
Referenced by pairinteraction::Basis< Derived >::get_indices_of_blocks(), and pairinteraction::Basis< Derived >::get_sorter().
set_coefficients()
template<typename Derived > void pairinteraction::Basis< Derived >::set_coefficients (const Eigen::SparseMatrix< scalar_t, Eigen::RowMajor > & values)
Definition at line 131 of file Basis.cpp.
transformed() [1/2]
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::transformed (const Sorting & transformation) const
Definition at line 605 of file Basis.cpp.
References pairinteraction::Transformation< Scalar >::matrix, pairinteraction::Sorting::matrix, pairinteraction::Sorting::transformation_type, and pairinteraction::Basis< Derived >::transformed().
transformed() [2/2]
template<typename Derived > std::shared_ptr< const Derived > pairinteraction::Basis< Derived >::transformed (const Transformation< scalar_t > & transformation) const
Definition at line 640 of file Basis.cpp.
References pairinteraction::utils::is_sorting(), pairinteraction::Transformation< Scalar >::matrix, pairinteraction::ROTATE, pairinteraction::Transformation< Scalar >::transformation_type, pairinteraction::Basis< Derived >::transformed(), and pairinteraction::UNKNOWN.
Referenced by pairinteraction::Basis< Derived >::transformed().
Field Documentation
kets
template<typename Derived > ketvec_t pairinteraction::Basis< Derived >::kets protected
Definition at line 122 of file Basis.hpp.
Referenced by pairinteraction::Basis< Derived >::get_rotator().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/basis/Basis.hpp
/__w/pairinteraction/pairinteraction/src/cpp/src/basis/Basis.cpp