pairinteraction: Cache< Key, Element, Hash > Class Template Reference
Cache< Key, Element, Hash > Class Template Reference
Generic cache object.
#include <Cache.hpp>
Public Member Functions
void save (Key const &key, Element const &e)
Save something in the cache.
std::optional< Element > restore (Key const &key)
Restore something from the cache.
void clear ()
Clear the cache.
Detailed Description
template<typename Key, typename Element, typename Hash = std::hash<Key>>
class Cache< Key, Element, Hash >
Generic cache object.
This generic cache object strives to provide a thread-safe cache based on a std::unordered_map protected from smashing by a mutex.
There are only few public methods, which are save, restore, and clear. Iteration over the cache was left out intentionally as the user should not search the cache manually for entries.
Definition at line 38 of file Cache.hpp.
Member Function Documentation
clear()
template<typename Key , typename Element , typename Hash = std::hash<Key>> void Cache< Key, Element, Hash >::clear () inline
Clear the cache.
Delete all elements in the cache
Definition at line 100 of file Cache.hpp.
Referenced by TEST_CASE().
restore()
template<typename Key , typename Element , typename Hash = std::hash<Key>> std::optional<Element> Cache< Key, Element, Hash >::restore (Key const & key) inline
Restore something from the cache.
When restoring from the cache, the situation might occur that an element is not yet available in the cache. We do not want to throw an exception in that case because that case might be very frequent when building the cache. Therefore restoring returns an optional value, i.e. it might not void. Hence the access pattern is also a little different.
if (auto optional_element = cache.restore(key,element)) {
    // Cache hit!  Restore cache...
    element = optional_element.get();
} else {
    // Cache miss :-(
}
Parameters
key Key
Returns
Optional element
Definition at line 87 of file Cache.hpp.
Referenced by TEST_CASE().
save()
template<typename Key , typename Element , typename Hash = std::hash<Key>> void Cache< Key, Element, Hash >::save (Key const & key, Element const & e) inline
Save something in the cache.
To prevent race-conditions this function will throw if the element is already in the cache.
The usage is extremely straight-forward
cache.save(key,element);
Parameters
key Key
e Element
Exceptions
std::runtime_error if the element is already in the cache
Definition at line 59 of file Cache.hpp.
Referenced by TEST_CASE().
The documentation for this class was generated from the following file:
/__w/pairinteraction/pairinteraction/pairinteraction/Cache.hpp