pairinteraction: pairinteraction::KetAtomCreator Class Reference
pairinteraction::KetAtomCreator Class Reference
Builder class for creating KetAtom objects.
#include <KetAtomCreator.hpp>
Public Member Functions
KetAtomCreator ()=default
KetAtomCreator (std::string species, int n, double l, double j, double m)
KetAtomCreator & set_species (const std::string &value)
KetAtomCreator & set_energy (double value)
KetAtomCreator & set_quantum_number_f (double value)
KetAtomCreator & set_quantum_number_m (double value)
KetAtomCreator & set_parity (Parity value)
KetAtomCreator & set_quantum_number_n (int value)
KetAtomCreator & set_quantum_number_nu (double value)
KetAtomCreator & set_quantum_number_nui (double value)
KetAtomCreator & set_quantum_number_l (double value)
KetAtomCreator & set_quantum_number_s (double value)
KetAtomCreator & set_quantum_number_j (double value)
KetAtomCreator & set_quantum_number_l_ryd (double value)
KetAtomCreator & set_quantum_number_j_ryd (double value)
std::shared_ptr< const KetAtom > create (Database &database) const
Detailed Description
Builder class for creating KetAtom objects.
Definition at line 23 of file KetAtomCreator.hpp.
Constructor & Destructor Documentation
KetAtomCreator() [1/2]
pairinteraction::KetAtomCreator::KetAtomCreator () default
KetAtomCreator() [2/2]
pairinteraction::KetAtomCreator::KetAtomCreator (std::string species, int n, double l, double j, double m)
Definition at line 13 of file KetAtomCreator.cpp.
Member Function Documentation
create()
std::shared_ptr< const KetAtom > pairinteraction::KetAtomCreator::create (Database & database) const
Definition at line 88 of file KetAtomCreator.cpp.
References pairinteraction::Database::get_ket().
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
set_energy()
KetAtomCreator & pairinteraction::KetAtomCreator::set_energy (double value)
Definition at line 22 of file KetAtomCreator.cpp.
set_parity()
KetAtomCreator & pairinteraction::KetAtomCreator::set_parity (Parity value)
Definition at line 43 of file KetAtomCreator.cpp.
set_quantum_number_f()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_f (double value)
Definition at line 27 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE().
set_quantum_number_j()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_j (double value)
Definition at line 73 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
set_quantum_number_j_ryd()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_j_ryd (double value)
Definition at line 83 of file KetAtomCreator.cpp.
set_quantum_number_l()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_l (double value)
Definition at line 63 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
set_quantum_number_l_ryd()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_l_ryd (double value)
Definition at line 78 of file KetAtomCreator.cpp.
set_quantum_number_m()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_m (double value)
Definition at line 35 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
set_quantum_number_n()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_n (int value)
Definition at line 48 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
set_quantum_number_nu()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_nu (double value)
Definition at line 53 of file KetAtomCreator.cpp.
set_quantum_number_nui()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_nui (double value)
Definition at line 58 of file KetAtomCreator.cpp.
set_quantum_number_s()
KetAtomCreator & pairinteraction::KetAtomCreator::set_quantum_number_s (double value)
Definition at line 68 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE().
set_species()
KetAtomCreator & pairinteraction::KetAtomCreator::set_species (const std::string & value)
Definition at line 17 of file KetAtomCreator.cpp.
Referenced by pairinteraction::DOCTEST_TEST_CASE(), and main().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/src/cpp/include/pairinteraction/ket/KetAtomCreator.hpp
/__w/pairinteraction/pairinteraction/src/cpp/src/ket/KetAtomCreator.cpp