pairinteraction: StateTwo Class Reference
StateTwo Class Reference
Two-atom state This class implements a two-atom state. It can either be a Rydberg state in the fine structure basis or an artificial state specified by a label.
#include <State.hpp>
Public Member Functions
StateTwo ()=default
StateTwo (std::array< std::string, 2 > species, std::array< int, 2 > n, std::array< int, 2 > l, std::array< float, 2 > j, std::array< float, 2 > m)
Implementation of two-atom state ///////////////////////////////.
StateTwo (std::array< std::string, 2 > label)
StateTwo (StateOne first_state, StateOne second_state)
std::string str () const
std::array< int, 2 > getN () const
std::array< int, 2 > getL () const
std::array< float, 2 > getJ () const
std::array< float, 2 > getM () const
std::array< float, 2 > getS () const
std::array< std::string, 2 > getSpecies () const
std::array< std::string, 2 > getElement () const
double getEnergy () const
double getEnergy (MatrixElementCache &cache) const
std::array< double, 2 > getNStar () const
std::array< double, 2 > getNStar (MatrixElementCache &cache) const
double getLeRoyRadius (MatrixElementCache &cache) const
std::array< std::string, 2 > getLabel () const
std::array< bool, 2 > isArtificial () const
std::array< bool, 2 > isGeneralized () const
const int & getN (int idx) const
const int & getL (int idx) const
const float & getJ (int idx) const
const float & getM (int idx) const
const float & getS (int idx) const
const std::string & getSpecies (int idx) const
const std::string & getElement (int idx) const
double getEnergy (int idx) const
double getEnergy (int idx, MatrixElementCache &cache) const
double getNStar (int idx) const
double getNStar (int idx, MatrixElementCache &cache) const
const std::string & getLabel (int idx) const
bool isArtificial (int idx) const
bool isGeneralized (int idx) const
const StateOne & getFirstState () const
const StateOne & getSecondState () const
const size_t & getHash () const
StateTwo getReflected () const
bool operator== (StateTwo const &rhs) const
bool operator^ (StateTwo const &rhs) const
bool operator!= (StateTwo const &rhs) const
bool operator< (StateTwo const &rhs) const
bool operator<= (StateTwo const &rhs) const
Friends
class cereal::access
std::ostream & operator<< (std::ostream &out, const StateTwo &state)
Detailed Description
Two-atom state This class implements a two-atom state. It can either be a Rydberg state in the fine structure basis or an artificial state specified by a label.
Definition at line 106 of file State.hpp.
Constructor & Destructor Documentation
StateTwo() [1/4]
StateTwo::StateTwo () default
Referenced by getReflected().
StateTwo() [2/4]
StateTwo::StateTwo (std::array< std::string, 2 > species, std::array< int, 2 > n, std::array< int, 2 > l, std::array< float, 2 > j, std::array< float, 2 > m) explicit
Implementation of two-atom state ///////////////////////////////.
Definition at line 198 of file State.cpp.
StateTwo() [3/4]
StateTwo::StateTwo (std::array< std::string, 2 > label) explicit
Definition at line 206 of file State.cpp.
StateTwo() [4/4]
StateTwo::StateTwo (StateOne first_state, StateOne second_state) explicit
Definition at line 212 of file State.cpp.
Member Function Documentation
getElement() [1/2]
std::array< std::string, 2 > StateTwo::getElement () const
Definition at line 250 of file State.cpp.
getElement() [2/2]
const std::string & StateTwo::getElement (int idx) const
Definition at line 286 of file State.cpp.
getEnergy() [1/4]
double StateTwo::getEnergy () const
Definition at line 253 of file State.cpp.
Referenced by PerturbativeInteraction::getC6(), and TEST_CASE_FIXTURE().
getEnergy() [2/4]
double StateTwo::getEnergy (int idx) const
Definition at line 287 of file State.cpp.
getEnergy() [3/4]
double StateTwo::getEnergy (int idx, MatrixElementCache & cache) const
Definition at line 288 of file State.cpp.
getEnergy() [4/4]
double StateTwo::getEnergy (MatrixElementCache & cache) const
Definition at line 256 of file State.cpp.
getFirstState()
const StateOne & StateTwo::getFirstState () const
Definition at line 299 of file State.cpp.
Referenced by PerturbativeInteraction::getC6().
getHash()
const size_t & StateTwo::getHash () const
Definition at line 302 of file State.cpp.
Referenced by std::hash< StateTwo >::operator()().
getJ() [1/2]
std::array< float, 2 > StateTwo::getJ () const
Definition at line 238 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), PerturbativeInteraction::getC6(), and getReflected().
getJ() [2/2]
const float & StateTwo::getJ (int idx) const
Definition at line 282 of file State.cpp.
getL() [1/2]
std::array< int, 2 > StateTwo::getL () const
Definition at line 235 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), PerturbativeInteraction::getC6(), and getReflected().
getL() [2/2]
const int & StateTwo::getL (int idx) const
Definition at line 281 of file State.cpp.
getLabel() [1/2]
std::array< std::string, 2 > StateTwo::getLabel () const
Definition at line 270 of file State.cpp.
getLabel() [2/2]
const std::string & StateTwo::getLabel (int idx) const
Definition at line 295 of file State.cpp.
getLeRoyRadius()
double StateTwo::getLeRoyRadius (MatrixElementCache & cache) const
Definition at line 265 of file State.cpp.
References MatrixElementCache::getRadial().
getM() [1/2]
std::array< float, 2 > StateTwo::getM () const
Definition at line 241 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), PerturbativeInteraction::getC6(), and getReflected().
getM() [2/2]
const float & StateTwo::getM (int idx) const
Definition at line 283 of file State.cpp.
getN() [1/2]
std::array< int, 2 > StateTwo::getN () const
Definition at line 232 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), PerturbativeInteraction::getC6(), and getReflected().
getN() [2/2]
const int & StateTwo::getN (int idx) const
Definition at line 280 of file State.cpp.
getNStar() [1/4]
std::array< double, 2 > StateTwo::getNStar () const
Definition at line 259 of file State.cpp.
getNStar() [2/4]
double StateTwo::getNStar (int idx) const
Definition at line 291 of file State.cpp.
getNStar() [3/4]
double StateTwo::getNStar (int idx, MatrixElementCache & cache) const
Definition at line 292 of file State.cpp.
getNStar() [4/4]
std::array< double, 2 > StateTwo::getNStar (MatrixElementCache & cache) const
Definition at line 262 of file State.cpp.
getReflected()
StateTwo StateTwo::getReflected () const
Definition at line 304 of file State.cpp.
References getJ(), getL(), getM(), getN(), getSpecies(), and StateTwo().
getS() [1/2]
std::array< float, 2 > StateTwo::getS () const
Definition at line 244 of file State.cpp.
Referenced by PerturbativeInteraction::getC6().
getS() [2/2]
const float & StateTwo::getS (int idx) const
Definition at line 284 of file State.cpp.
getSecondState()
const StateOne & StateTwo::getSecondState () const
Definition at line 300 of file State.cpp.
Referenced by PerturbativeInteraction::getC6().
getSpecies() [1/2]
std::array< std::string, 2 > StateTwo::getSpecies () const
Definition at line 247 of file State.cpp.
Referenced by PerturbativeInteraction::getC6(), and getReflected().
getSpecies() [2/2]
const std::string & StateTwo::getSpecies (int idx) const
Definition at line 285 of file State.cpp.
isArtificial() [1/2]
std::array< bool, 2 > StateTwo::isArtificial () const
Definition at line 273 of file State.cpp.
isArtificial() [2/2]
bool StateTwo::isArtificial (int idx) const
Definition at line 296 of file State.cpp.
isGeneralized() [1/2]
std::array< bool, 2 > StateTwo::isGeneralized () const
Definition at line 276 of file State.cpp.
isGeneralized() [2/2]
bool StateTwo::isGeneralized (int idx) const
Definition at line 297 of file State.cpp.
operator!=()
bool StateTwo::operator!= (StateTwo const & rhs) const
Definition at line 316 of file State.cpp.
operator<()
bool StateTwo::operator< (StateTwo const & rhs) const
Definition at line 319 of file State.cpp.
operator<=()
bool StateTwo::operator<= (StateTwo const & rhs) const
Definition at line 323 of file State.cpp.
operator==()
bool StateTwo::operator== (StateTwo const & rhs) const
Definition at line 310 of file State.cpp.
operator^()
bool StateTwo::operator^ (StateTwo const & rhs) const
Definition at line 313 of file State.cpp.
str()
std::string StateTwo::str () const
Definition at line 225 of file State.cpp.
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Definition at line 171 of file State.hpp.
operator<<
std::ostream& operator<< (std::ostream & out, const StateTwo & state) friend
Definition at line 220 of file State.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/State.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/State.cpp