pairinteraction: HamiltonianOne< Scalar > Class Template Reference
HamiltonianOne< Scalar > Class Template Reference
#include <HamiltonianOne.hpp>
Public Member Functions
HamiltonianOne (const Configuration &config, fs::path &path_cache, std::shared_ptr< BasisnamesOne > basis_one)
const Configuration & getConf () const
Public Member Functions inherited from Hamiltonian< Scalar, BasisnamesOne >
Hamiltonian ()=default
std::shared_ptr< Hamiltonianmatrix< Scalar > > get (size_t idx)
std::shared_ptr< const Hamiltonianmatrix< Scalar > > get (size_t idx) const
std::shared_ptr< const Configuration > getParams (size_t idx) const
size_t size () const
std::shared_ptr< const BasisnamesOne > names () const
void removeUnnecessaryStates (std::vector< bool > &necessary)
Protected Member Functions
void changeToSpherical (double val_x, double val_y, double val_z, double &val_p, double &val_m, double &val_0)
void changeToSpherical (double val_x, double val_y, double val_z, std::complex< double > &val_p, std::complex< double > &val_m, std::complex< double > &val_0)
void configure (const Configuration &config)
void build ()
Additional Inherited Members
Protected Attributes inherited from Hamiltonian< Scalar, BasisnamesOne >
std::vector< std::shared_ptr< Hamiltonianmatrix< Scalar > > > matrix_diag
std::vector< std::string > matrix_path
std::vector< std::shared_ptr< Configuration > > params
std::shared_ptr< BasisnamesOne > basis
Detailed Description
template<typename Scalar>
class HamiltonianOne< Scalar >
Definition at line 39 of file HamiltonianOne.hpp.
Constructor & Destructor Documentation
HamiltonianOne()
template<typename Scalar > HamiltonianOne< Scalar >::HamiltonianOne (const Configuration & config, fs::path & path_cache, std::shared_ptr< BasisnamesOne > basis_one)
Definition at line 29 of file HamiltonianOne.cpp.
References Hamiltonian< Scalar, BasisnamesOne >::basis, HamiltonianOne< Scalar >::build(), and HamiltonianOne< Scalar >::configure().
Member Function Documentation
build()
template<typename Scalar > void HamiltonianOne< Scalar >::build protected
Definition at line 99 of file HamiltonianOne.cpp.
References Hamiltonianmatrix< Scalar >::addBasis(), Hamiltonianmatrix< Scalar >::addEntries(), Hamiltonianmatrix< Scalar >::compress(), Hamiltonianmatrix< Scalar >::diagonalize(), energy_level(), sqlite::statement::exec(), sqlite::statement::get(), MatrixElements::getDiamagnetism(), MatrixElements::getElectricMomentum(), MatrixElements::getMagneticMomentum(), Hamiltonianmatrix< Scalar >::load(), Configuration::load_from_json(), Hamiltonianmatrix< Scalar >::num_basisvectors(), MatrixElements::precalculateDiamagnetism(), MatrixElements::precalculateElectricMomentum(), MatrixElements::precalculateMagneticMomentum(), sqlite::statement::prepare(), Hamiltonianmatrix< Scalar >::save(), selectionRulesMomentum(), selectionRulesMultipole(), and sqlite::statement::step().
Referenced by HamiltonianOne< Scalar >::HamiltonianOne().
changeToSpherical() [1/2]
template<typename Scalar > void HamiltonianOne< Scalar >::changeToSpherical (double val_x, double val_y, double val_z, double & val_p, double & val_m, double & val_0) protected
Definition at line 44 of file HamiltonianOne.cpp.
changeToSpherical() [2/2]
template<typename Scalar > void HamiltonianOne< Scalar >::changeToSpherical (double val_x, double val_y, double val_z, std::complex< double > & val_p, std::complex< double > & val_m, std::complex< double > & val_0) protected
Definition at line 57 of file HamiltonianOne.cpp.
configure()
template<typename Scalar > void HamiltonianOne< Scalar >::configure (const Configuration & config) protected
Definition at line 67 of file HamiltonianOne.cpp.
Referenced by HamiltonianOne< Scalar >::HamiltonianOne().
getConf()
template<typename Scalar > const Configuration & HamiltonianOne< Scalar >::getConf
Definition at line 38 of file HamiltonianOne.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/HamiltonianOne.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/HamiltonianOne.cpp