pairinteraction: GreenTensor Class Reference
GreenTensor Class Reference
#include <GreenTensor.hpp>
Public Types
using TensorType = Eigen::TensorFixedSize< double, Eigen::Sizes< 3, 3, 3 > >
Public Member Functions
GreenTensor (double x, double y, double z)
void addSurface (double d)
const Eigen::Matrix3< double > & getDDTensor ()
const TensorType & getDQTensor ()
const TensorType & getQDTensor ()
Detailed Description
Definition at line 30 of file GreenTensor.hpp.
Member Typedef Documentation
TensorType
using GreenTensor::TensorType = Eigen::TensorFixedSize<double, Eigen::Sizes<3, 3, 3> >
Definition at line 33 of file GreenTensor.hpp.
Constructor & Destructor Documentation
GreenTensor()
GreenTensor::GreenTensor (double x, double y, double z)
Definition at line 30 of file GreenTensor.cpp.
Member Function Documentation
addSurface()
void GreenTensor::addSurface (double d)
Definition at line 35 of file GreenTensor.cpp.
Referenced by SystemTwo< Scalar_ >::initializeInteraction().
getDDTensor()
const Eigen::Matrix3< double > & GreenTensor::getDDTensor ()
Definition at line 55 of file GreenTensor.cpp.
Referenced by SystemTwo< Scalar_ >::initializeInteraction().
getDQTensor()
const TensorType & GreenTensor::getDQTensor ()
Definition at line 67 of file GreenTensor.cpp.
Referenced by SystemTwo< Scalar_ >::initializeInteraction().
getQDTensor()
const TensorType & GreenTensor::getQDTensor ()
Definition at line 78 of file GreenTensor.cpp.
Referenced by SystemTwo< Scalar_ >::initializeInteraction().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/GreenTensor.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/GreenTensor.cpp