pairinteraction: BasisnamesTwo Class Reference
BasisnamesTwo Class Reference
#include <Basisnames.hpp>
Public Member Functions
BasisnamesTwo (const std::shared_ptr< const BasisnamesOne > &basis_one1, const std::shared_ptr< const BasisnamesOne > &basis_one2)
BasisnamesTwo (const std::shared_ptr< const BasisnamesOne > &basis_one1)
const StateTwoOld & initial () const
void removeUnnecessaryStates (const std::vector< bool > &is_necessary)
void removeUnnecessaryStatesKeepIdx (const std::vector< bool > &is_necessary)
void save (const std::string &path)
Public Member Functions inherited from Basisnames< StateTwoOld >
Basisnames ()=default
void configure (const Configuration &config)
size_t size () const
size_t dim () const
StateTwoOld & get (size_t idx)
const StateTwoOld & get (size_t idx) const
void set (size_t i, const StateTwoOld &v)
ConstIter< Basisnames, StateTwoOld > begin () const
ConstIter< Basisnames, StateTwoOld > end () const
const Configuration & getConf () const
Protected Member Functions
void build (StateTwoOld startstate, std::array< std::string, 2 > species, const std::shared_ptr< const BasisnamesOne > &basis_one1, const std::shared_ptr< const BasisnamesOne > &basis_one2)
Additional Inherited Members
Protected Attributes inherited from Basisnames< StateTwoOld >
int delta_n
int delta_l
int delta_j
int delta_m
Configuration conf
std::vector< StateTwoOld > names_
size_t dim_
Detailed Description
Definition at line 96 of file Basisnames.hpp.
Constructor & Destructor Documentation
BasisnamesTwo() [1/2]
BasisnamesTwo::BasisnamesTwo (const std::shared_ptr< const BasisnamesOne > & basis_one1, const std::shared_ptr< const BasisnamesOne > & basis_one2)
Definition at line 322 of file Basisnames.cpp.
References build(), Basisnames< StateTwoOld >::conf, Basisnames< StateTwoOld >::configure(), StateTwoOld::j, StateTwoOld::l, StateTwoOld::m, and StateTwoOld::n.
BasisnamesTwo() [2/2]
BasisnamesTwo::BasisnamesTwo (const std::shared_ptr< const BasisnamesOne > & basis_one1)
Definition at line 295 of file Basisnames.cpp.
References build(), Basisnames< StateTwoOld >::conf, Basisnames< StateTwoOld >::configure(), StateTwoOld::j, StateTwoOld::l, StateTwoOld::m, and StateTwoOld::n.
Member Function Documentation
build()
void BasisnamesTwo::build (StateTwoOld startstate, std::array< std::string, 2 > species, const std::shared_ptr< const BasisnamesOne > & basis_one1, const std::shared_ptr< const BasisnamesOne > & basis_one2) protected
Definition at line 393 of file Basisnames.cpp.
References Basisnames< StateTwoOld >::conf, Basisnames< StateTwoOld >::dim_, StateOld::idx, StateTwoOld::j, StateTwoOld::l, StateTwoOld::m, StateTwoOld::n, Basisnames< StateTwoOld >::names_, and Basisnames< StateTwoOld >::size().
Referenced by BasisnamesTwo().
initial()
const StateTwoOld & BasisnamesTwo::initial () const
Definition at line 351 of file Basisnames.cpp.
removeUnnecessaryStates()
void BasisnamesTwo::removeUnnecessaryStates (const std::vector< bool > & is_necessary)
Definition at line 353 of file Basisnames.cpp.
References Basisnames< StateTwoOld >::dim_, StateOld::idx, and Basisnames< StateTwoOld >::names_.
removeUnnecessaryStatesKeepIdx()
void BasisnamesTwo::removeUnnecessaryStatesKeepIdx (const std::vector< bool > & is_necessary)
Definition at line 379 of file Basisnames.cpp.
References Basisnames< StateTwoOld >::names_.
save()
void BasisnamesTwo::save (const std::string & path)
Definition at line 432 of file Basisnames.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/Basisnames.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/Basisnames.cpp