pairinteraction: MatrixElements Class Reference
MatrixElements Class Reference
#include <MatrixElements.hpp>
Public Member Functions
MatrixElements (std::string const &species, std::string dbname)
MatrixElements (const Configuration &config, std::string const &species, std::string const &dbname)
void precalculateElectricMomentum (std::shared_ptr< const BasisnamesOne > const &basis_one, int q)
void precalculateMagneticMomentum (std::shared_ptr< const BasisnamesOne > const &basis_one, int q)
void precalculateDiamagnetism (std::shared_ptr< const BasisnamesOne > const &basis_one, int k, int q)
void precalculateMultipole (std::shared_ptr< const BasisnamesOne > const &basis_one, int k)
void precalculateRadial (std::shared_ptr< const BasisnamesOne > const &basis_one, int k)
double getElectricMomentum (StateOneOld const &state_row, StateOneOld const &state_col)
double getMagneticMomentum (StateOneOld const &state_row, StateOneOld const &state_col)
double getDiamagnetism (StateOneOld const &state_row, StateOneOld const &state_col, int k)
double getMultipole (StateOneOld const &state_row, StateOneOld const &state_col, int k)
double getRadial (StateOneOld const &state_row, StateOneOld const &state_col, int k)
void precalculateElectricMomentum (const std::vector< StateOneOld > &basis_one, int q)
void precalculateMagneticMomentum (const std::vector< StateOneOld > &basis_one, int q)
void precalculateDiamagnetism (const std::vector< StateOneOld > &basis_one, int k, int q)
void precalculateMultipole (const std::vector< StateOneOld > &basis_one, int k)
void precalculateRadial (const std::vector< StateOneOld > &basis_one, int k)
Detailed Description
Definition at line 40 of file MatrixElements.hpp.
Constructor & Destructor Documentation
MatrixElements() [1/2]
MatrixElements::MatrixElements (std::string const & species, std::string dbname)
Definition at line 73 of file MatrixElements.cpp.
MatrixElements() [2/2]
MatrixElements::MatrixElements (const Configuration & config, std::string const & species, std::string const & dbname)
Definition at line 86 of file MatrixElements.cpp.
Member Function Documentation
getDiamagnetism()
double MatrixElements::getDiamagnetism (StateOneOld const & state_row, StateOneOld const & state_col, int k)
Definition at line 155 of file MatrixElements.cpp.
References elementary_charge, inverse_electron_rest_mass, StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
Referenced by HamiltonianOne< Scalar >::build().
getElectricMomentum()
double MatrixElements::getElectricMomentum (StateOneOld const & state_row, StateOneOld const & state_col)
Definition at line 125 of file MatrixElements.cpp.
References getMultipole().
Referenced by HamiltonianOne< Scalar >::build().
getMagneticMomentum()
double MatrixElements::getMagneticMomentum (StateOneOld const & state_row, StateOneOld const & state_col)
Definition at line 132 of file MatrixElements.cpp.
References au2G, au2GHz, StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
Referenced by HamiltonianOne< Scalar >::build().
getMultipole()
double MatrixElements::getMultipole (StateOneOld const & state_row, StateOneOld const & state_col, int k)
Definition at line 173 of file MatrixElements.cpp.
References StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
Referenced by HamiltonianTwo< Scalar >::calculate(), and getElectricMomentum().
getRadial()
double MatrixElements::getRadial (StateOneOld const & state_row, StateOneOld const & state_col, int k)
Definition at line 188 of file MatrixElements.cpp.
References StateOneOld::j, StateOneOld::l, and StateOneOld::n.
precalculateDiamagnetism() [1/2]
void MatrixElements::precalculateDiamagnetism (const std::vector< StateOneOld > & basis_one, int k, int q)
Definition at line 601 of file MatrixElements.cpp.
precalculateDiamagnetism() [2/2]
void MatrixElements::precalculateDiamagnetism (std::shared_ptr< const BasisnamesOne > const & basis_one, int k, int q)
Definition at line 120 of file MatrixElements.cpp.
Referenced by HamiltonianOne< Scalar >::build().
precalculateElectricMomentum() [1/2]
void MatrixElements::precalculateElectricMomentum (const std::vector< StateOneOld > & basis_one, int q)
Definition at line 591 of file MatrixElements.cpp.
precalculateElectricMomentum() [2/2]
void MatrixElements::precalculateElectricMomentum (std::shared_ptr< const BasisnamesOne > const & basis_one, int q)
Definition at line 110 of file MatrixElements.cpp.
Referenced by HamiltonianOne< Scalar >::build().
precalculateMagneticMomentum() [1/2]
void MatrixElements::precalculateMagneticMomentum (const std::vector< StateOneOld > & basis_one, int q)
Definition at line 596 of file MatrixElements.cpp.
precalculateMagneticMomentum() [2/2]
void MatrixElements::precalculateMagneticMomentum (std::shared_ptr< const BasisnamesOne > const & basis_one, int q)
Definition at line 115 of file MatrixElements.cpp.
Referenced by HamiltonianOne< Scalar >::build().
precalculateMultipole() [1/2]
void MatrixElements::precalculateMultipole (const std::vector< StateOneOld > & basis_one, int k)
Definition at line 581 of file MatrixElements.cpp.
precalculateMultipole() [2/2]
void MatrixElements::precalculateMultipole (std::shared_ptr< const BasisnamesOne > const & basis_one, int k)
Definition at line 98 of file MatrixElements.cpp.
Referenced by HamiltonianTwo< Scalar >::calculate().
precalculateRadial() [1/2]
void MatrixElements::precalculateRadial (const std::vector< StateOneOld > & basis_one, int k)
Definition at line 586 of file MatrixElements.cpp.
precalculateRadial() [2/2]
void MatrixElements::precalculateRadial (std::shared_ptr< const BasisnamesOne > const & basis_one, int k)
Definition at line 104 of file MatrixElements.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/MatrixElements.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/MatrixElements.cpp