pairinteraction: StateOne Class Reference
StateOne Class Reference
One-atom state This class implements a one-atom state. It can either be a Rydberg state in the fine structure basis or an artificial state specified by a label.
#include <State.hpp>
Public Member Functions
StateOne ()=default
StateOne (std::string species, int n, int l, float j, float m)
Implementation of one-atom state ///////////////////////////////.
StateOne (std::string label)
std::string str () const
const int & getN () const
const int & getL () const
const float & getJ () const
const float & getM () const
const float & getS () const
const std::string & getSpecies () const
const std::string & getElement () const
double getEnergy () const
double getEnergy (MatrixElementCache &cache) const
double getNStar () const
double getNStar (MatrixElementCache &cache) const
const std::string & getLabel () const
bool isArtificial () const
bool isGeneralized () const
const size_t & getHash () const
StateOne getReflected () const
bool operator== (StateOne const &rhs) const
bool operator^ (StateOne const &rhs) const
bool operator!= (StateOne const &rhs) const
bool operator< (StateOne const &rhs) const
bool operator<= (StateOne const &rhs) const
Friends
class cereal::access
std::ostream & operator<< (std::ostream &out, const StateOne &state)
Detailed Description
One-atom state This class implements a one-atom state. It can either be a Rydberg state in the fine structure basis or an artificial state specified by a label.
Definition at line 42 of file State.hpp.
Constructor & Destructor Documentation
StateOne() [1/3]
StateOne::StateOne () default
Referenced by getReflected().
StateOne() [2/3]
StateOne::StateOne (std::string species, int n, int l, float j, float m) explicit
Implementation of one-atom state ///////////////////////////////.
Definition at line 56 of file State.cpp.
References getJ(), getL(), getM(), getN(), getSpecies(), and utils::hash_combine().
StateOne() [3/3]
StateOne::StateOne (std::string label) explicit
Definition at line 67 of file State.cpp.
References getLabel().
Member Function Documentation
getElement()
const std::string & StateOne::getElement () const
Definition at line 123 of file State.cpp.
getEnergy() [1/2]
double StateOne::getEnergy () const
Definition at line 127 of file State.cpp.
References energy_level().
Referenced by SystemOne< Scalar_ >::initializeBasis(), and TEST_CASE_FIXTURE().
getEnergy() [2/2]
double StateOne::getEnergy (MatrixElementCache & cache) const
Definition at line 131 of file State.cpp.
References energy_level(), and MatrixElementCache::getDefectDB().
getHash()
const size_t & StateOne::getHash () const
Definition at line 152 of file State.cpp.
Referenced by std::hash< StateOne >::operator()().
getJ()
const float & StateOne::getJ () const
Definition at line 107 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), MatrixElementCache::getElectricMultipole(), MatrixElementCache::getMagneticDipole(), MatrixElementCache::getRadial(), getReflected(), SystemTwo< Scalar_ >::initializeBasis(), selectionRulesMomentumNew(), selectionRulesMultipoleNew(), and StateOne().
getL()
const int & StateOne::getL () const
Definition at line 103 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), MatrixElementCache::getElectricMultipole(), MatrixElementCache::getMagneticDipole(), MatrixElementCache::getRadial(), getReflected(), SystemTwo< Scalar_ >::initializeBasis(), selectionRulesMomentumNew(), selectionRulesMultipoleNew(), StateOne(), and TEST_CASE_FIXTURE().
getLabel()
const std::string & StateOne::getLabel () const
Definition at line 143 of file State.cpp.
Referenced by StateOne().
getM()
const float & StateOne::getM () const
Definition at line 111 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), MatrixElementCache::getElectricMultipole(), MatrixElementCache::getMagneticDipole(), getReflected(), SystemOne< Scalar_ >::initializeBasis(), SystemTwo< Scalar_ >::initializeBasis(), selectionRulesMomentumNew(), selectionRulesMultipoleNew(), and StateOne().
getN()
const int & StateOne::getN () const
Definition at line 99 of file State.cpp.
Referenced by SystemBase< Scalar, State >::checkIsQuantumstateValid(), MatrixElementCache::getElectricMultipole(), MatrixElementCache::getMagneticDipole(), MatrixElementCache::getRadial(), getReflected(), StateOne(), and TEST_CASE_FIXTURE().
getNStar() [1/2]
double StateOne::getNStar () const
Definition at line 135 of file State.cpp.
References nstar().
getNStar() [2/2]
double StateOne::getNStar (MatrixElementCache & cache) const
Definition at line 139 of file State.cpp.
References MatrixElementCache::getDefectDB(), and nstar().
getReflected()
StateOne StateOne::getReflected () const
Definition at line 154 of file State.cpp.
References getJ(), getL(), getM(), getN(), getSpecies(), and StateOne().
Referenced by SystemTwo< Scalar_ >::initializeBasis().
getS()
const float & StateOne::getS () const
Definition at line 115 of file State.cpp.
Referenced by MatrixElementCache::getElectricMultipole(), and MatrixElementCache::getMagneticDipole().
getSpecies()
const std::string & StateOne::getSpecies () const
Definition at line 119 of file State.cpp.
Referenced by MatrixElementCache::getElectricMultipole(), MatrixElementCache::getMagneticDipole(), MatrixElementCache::getRadial(), getReflected(), StateOne(), and TEST_CASE_FIXTURE().
isArtificial()
bool StateOne::isArtificial () const
Definition at line 147 of file State.cpp.
isGeneralized()
bool StateOne::isGeneralized () const
Definition at line 148 of file State.cpp.
References ARB.
operator!=()
bool StateOne::operator!= (StateOne const & rhs) const
Definition at line 167 of file State.cpp.
operator<()
bool StateOne::operator< (StateOne const & rhs) const
Definition at line 170 of file State.cpp.
operator<=()
bool StateOne::operator<= (StateOne const & rhs) const
Definition at line 177 of file State.cpp.
operator==()
bool StateOne::operator== (StateOne const & rhs) const
Definition at line 159 of file State.cpp.
operator^()
bool StateOne::operator^ (StateOne const & rhs) const
Definition at line 162 of file State.cpp.
References ARB.
str()
std::string StateOne::str () const
Definition at line 92 of file State.cpp.
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Definition at line 88 of file State.hpp.
operator<<
std::ostream& operator<< (std::ostream & out, const StateOne & state) friend
Definition at line 73 of file State.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/State.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/State.cpp