pairinteraction: HamiltonianTwo< Scalar > Class Template Reference
HamiltonianTwo< Scalar > Class Template Reference
#include <HamiltonianTwo.hpp>
Public Member Functions
HamiltonianTwo (const Configuration &config, fs::path &path_cache, const std::shared_ptr< HamiltonianOne< Scalar >> &hamiltonian_one)
HamiltonianTwo (const Configuration &config, fs::path &path_cache, std::shared_ptr< HamiltonianOne< Scalar >> hamiltonian_one1, std::shared_ptr< HamiltonianOne< Scalar >> hamiltonian_one2)
void calculate (const Configuration &conf_tot)
Public Member Functions inherited from Hamiltonian< Scalar, BasisnamesTwo >
Hamiltonian ()=default
std::shared_ptr< Hamiltonianmatrix< Scalar > > get (size_t idx)
std::shared_ptr< const Hamiltonianmatrix< Scalar > > get (size_t idx) const
std::shared_ptr< const Configuration > getParams (size_t idx) const
size_t size () const
std::shared_ptr< const BasisnamesTwo > names () const
void removeUnnecessaryStates (std::vector< bool > &necessary)
Additional Inherited Members
Protected Attributes inherited from Hamiltonian< Scalar, BasisnamesTwo >
std::vector< std::shared_ptr< Hamiltonianmatrix< Scalar > > > matrix_diag
std::vector< std::string > matrix_path
std::vector< std::shared_ptr< Configuration > > params
std::shared_ptr< BasisnamesTwo > basis
Detailed Description
template<typename Scalar>
class HamiltonianTwo< Scalar >
Definition at line 41 of file HamiltonianTwo.hpp.
Constructor & Destructor Documentation
HamiltonianTwo() [1/2]
template<typename Scalar > HamiltonianTwo< Scalar >::HamiltonianTwo (const Configuration & config, fs::path & path_cache, const std::shared_ptr< HamiltonianOne< Scalar >> & hamiltonian_one)
Definition at line 30 of file HamiltonianTwo.cpp.
References HamiltonianTwo< Scalar >::calculate().
HamiltonianTwo() [2/2]
template<typename Scalar > HamiltonianTwo< Scalar >::HamiltonianTwo (const Configuration & config, fs::path & path_cache, std::shared_ptr< HamiltonianOne< Scalar >> hamiltonian_one1, std::shared_ptr< HamiltonianOne< Scalar >> hamiltonian_one2)
Definition at line 42 of file HamiltonianTwo.cpp.
References HamiltonianTwo< Scalar >::calculate().
Member Function Documentation
calculate()
template<typename Scalar > void HamiltonianTwo< Scalar >::calculate (const Configuration & conf_tot)
Definition at line 54 of file HamiltonianTwo.cpp.
References Hamiltonianmatrix< Scalar >::basis(), Hamiltonianmatrix< Scalar >::changeBasis(), combine(), Hamiltonianmatrix< Scalar >::diagonalize(), energycutoff(), EVEN, sqlite::statement::exec(), StateTwoOld::first(), BasisnamesOne::fromFirst(), BasisnamesOne::fromSecond(), sqlite::statement::get(), MatrixElements::getMultipole(), inverse_electric_constant, Symmetry::inversion, StateTwoOld::j, StateTwoOld::l, Hamiltonianmatrix< Scalar >::load(), Configuration::load_from_json(), StateTwoOld::m, NA, Hamiltonianmatrix< Scalar >::num_basisvectors(), ODD, Symmetry::permutation, MatrixElements::precalculateMultipole(), sqlite::statement::prepare(), Symmetry::reflection, Hamiltonianmatrix< Scalar >::removeUnnecessaryBasisvectors(), Symmetry::rotation, Hamiltonianmatrix< Scalar >::save(), StateTwoOld::second(), selectionRulesMultipole(), and sqlite::statement::step().
Referenced by HamiltonianTwo< Scalar >::HamiltonianTwo().
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/HamiltonianTwo.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/HamiltonianTwo.cpp