pairinteraction: SystemBase< Scalar, State > Class Template Reference
SystemBase< Scalar, State > Class Template Reference abstract
#include <SystemBase.hpp>
Public Member Functions
virtual ~SystemBase ()=default
void setMinimalNorm (const double &threshold)
void restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
void restrictN (int n_min, int n_max)
void restrictN (std::set< int > n)
void restrictL (int l_min, int l_max)
void restrictL (std::set< int > l)
void restrictJ (float j_min, float j_max)
void restrictJ (std::set< float > j)
void restrictM (float m_min, float m_max)
void restrictM (std::set< float > m)
void addStates (const State &s)
Method for adding user-defined states //////////////////////////.
void addStates (const std::set< State > &s)
Eigen::VectorX< double > getOverlap (const State &generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
Eigen::VectorX< double > getOverlap (const std::vector< State > &generalizedstates)
Eigen::VectorX< double > getOverlap (const size_t &state_index)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices)
Eigen::VectorX< double > getOverlap (const State &generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const std::vector< State > &generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const size_t &state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Eigen::VectorX< double > getOverlap (const State &generalizedstate, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const size_t &state_index, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const std::vector< State > &generalizedstates, double alpha, double beta, double gamma)
Eigen::VectorX< double > getOverlap (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)
std::vector< State > getStates ()
Methods to get properties of the system ////////////////////////.
const states_set< State >::type & getStatesMultiIndex ()
Eigen::SparseMatrix< Scalar > & getBasisvectors ()
Eigen::SparseMatrix< Scalar > & getHamiltonian ()
size_t getNumBasisvectors ()
size_t getNumStates ()
std::vector< State > getMainStates ()
std::array< std::vector< size_t >, 2 > getConnections (SystemBase< Scalar, State > &system_to, double threshold)
void buildHamiltonian ()
Methods to build, transform, and destroy the system ////////////.
void buildInteraction ()
void buildBasis ()
void diagonalize (double energy_lower_bound, double energy_upper_bound)
void diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
void diagonalize ()
void diagonalize (double threshold)
void canonicalize ()
void unitarize ()
void rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
void rotate (double alpha, double beta, double gamma)
void add (SystemBase< Scalar, State > &system)
void constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
void applySchriefferWolffTransformation (SystemBase< Scalar, State > &system0)
size_t getStateIndex (const State &searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
std::vector< size_t > getStateIndex (const std::vector< State > &searched_states)
size_t getBasisvectorIndex (const State &searched_state)
std::vector< size_t > getBasisvectorIndex (const std::vector< State > &searched_states)
void forgetStatemixing ()
Scalar getHamiltonianEntry (const State &state_row, const State &state_col)
void setHamiltonianEntry (const State &state_row, const State &state_col, Scalar value)
void addHamiltonianEntry (const State &state_row, const State &state_col, Scalar value)
Protected Member Functions
SystemBase ()
SystemBase (MatrixElementCache &cache)
SystemBase (MatrixElementCache &cache, bool memory_saving)
virtual void initializeBasis ()=0
virtual void initializeInteraction ()=0
virtual void transformInteraction (const Eigen::SparseMatrix< Scalar > &transformator)=0
virtual void addInteraction ()=0
virtual void deleteInteraction ()=0
virtual Eigen::SparseMatrix< Scalar > rotateStates (const std::vector< size_t > &states_indices, double alpha, double beta, double gamma)=0
virtual Eigen::SparseMatrix< Scalar > buildStaterotator (double alpha, double beta, double gamma)=0
virtual void incorporate (SystemBase< Scalar, State > &system)=0
virtual void onStatesChange ()
void onParameterChange ()
Helper method that shoul be called by the derived classes //////.
void onSymmetryChange ()
bool checkIsDiagonal (const Eigen::SparseMatrix< Scalar > &mat)
Helper methods to check diagonality and unitarity of a matrix //.
bool checkIsUnitary (const Eigen::SparseMatrix< Scalar > &mat)
template<class V >
bool checkIsQuantumnumberValid (V q, std::set< V > range_q)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const State &state)
Helper methods to check the validity of states /////////////////.
bool checkIsQuantumstateValid (const StateOne &state, bool a)
bool checkIsQuantumstateValid (const StateTwo &state, std::array< bool, 2 > a)
bool checkIsEnergyValid (double e)
void applyLeftsideTransformator (std::vector< Eigen::Triplet< Scalar >> &triplets_transformator)
Helper methods to change the set of basis vectors //////////////.
void applyLeftsideTransformator (Eigen::SparseMatrix< Scalar > &transformator)
void applyRightsideTransformator (std::vector< Eigen::Triplet< Scalar >> &triplets_transformator)
void applyRightsideTransformator (Eigen::SparseMatrix< Scalar > &transformator)
void removeRestrictedStates (std::function< bool(const enumerated_state< State > &)> checkIsValidEntry)
template<class V >
void range (std::set< V > &rset, V rmin, V rmax)
Utility methods ////////////////////////////////////////////////.
Eigen::Matrix< double, 3, 3 > buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Utility methods ////////////////////////////////////////////////.
Eigen::Matrix< double, 3, 3 > buildRotator (const double &alpha, const double &beta, const double &gamma)
Eigen::Matrix< double, 3, 1 > getEulerAngles (const std::array< double, 3 > &to_z_axis, const std::array< double, 3 > &to_y_axis)
Protected Attributes
MatrixElementCache * m_cache {nullptr}
double threshold_for_sqnorm {0.05}
double energy_min
double energy_max
std::set< int > range_n
std::set< int > range_l
std::set< float > range_j
std::set< float > range_m
std::set< State > states_to_add
bool memory_saving {false}
bool is_interaction_already_contained {false}
bool is_new_hamiltonian_required {false}
states_set< State >::type states
Eigen::SparseMatrix< Scalar > basisvectors
Eigen::SparseMatrix< Scalar > hamiltonian
Eigen::SparseMatrix< Scalar > basisvectors_unperturbed_cache
Eigen::SparseMatrix< Scalar > hamiltonian_unperturbed_cache
Friends
class cereal::access
Method for serialization ///////////////////////////////////////.
Detailed Description
template<class Scalar, class State>
class SystemBase< Scalar, State >
Definition at line 119 of file SystemBase.hpp.
Constructor & Destructor Documentation
~SystemBase()
template<class Scalar , class State > virtual SystemBase< Scalar, State >::~SystemBase () virtual default
SystemBase() [1/3]
template<class Scalar , class State > SystemBase< Scalar, State >::SystemBase protected
Definition at line 1294 of file SystemBase.cpp.
SystemBase() [2/3]
template<class Scalar , class State > SystemBase< Scalar, State >::SystemBase (MatrixElementCache & cache) protected
Definition at line 1299 of file SystemBase.cpp.
SystemBase() [3/3]
template<class Scalar , class State > SystemBase< Scalar, State >::SystemBase (MatrixElementCache & cache, bool memory_saving) protected
Definition at line 1304 of file SystemBase.cpp.
Member Function Documentation
add()
template<class Scalar , class State > void SystemBase< Scalar, State >::add (SystemBase< Scalar, State > & system)
Definition at line 835 of file SystemBase.cpp.
References SystemBase< Scalar, State >::basisvectors, SystemBase< Scalar, State >::basisvectors_unperturbed_cache, SystemBase< Scalar, State >::buildBasis(), SystemBase< Scalar, State >::hamiltonian, SystemBase< Scalar, State >::hamiltonian_unperturbed_cache, SystemBase< Scalar, State >::is_interaction_already_contained, SystemBase< Scalar, State >::is_new_hamiltonian_required, SystemBase< Scalar, State >::memory_saving, and SystemBase< Scalar, State >::states.
addHamiltonianEntry()
template<class Scalar , class State > void SystemBase< Scalar, State >::addHamiltonianEntry (const State & state_row, const State & state_col, Scalar value)
Definition at line 1275 of file SystemBase.cpp.
References utils::conjugate().
addInteraction()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::addInteraction () protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
addStates() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::addStates (const State & s)
Method for adding user-defined states //////////////////////////.
Definition at line 141 of file SystemBase.cpp.
addStates() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::addStates (const std::set< State > & s)
Definition at line 146 of file SystemBase.cpp.
applyLeftsideTransformator() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::applyLeftsideTransformator (Eigen::SparseMatrix< Scalar > & transformator) protected
Definition at line 1435 of file SystemBase.cpp.
applyLeftsideTransformator() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::applyLeftsideTransformator (std::vector< Eigen::Triplet< Scalar >> & triplets_transformator) protected
Helper methods to change the set of basis vectors //////////////.
Definition at line 1426 of file SystemBase.cpp.
applyRightsideTransformator() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::applyRightsideTransformator (Eigen::SparseMatrix< Scalar > & transformator) protected
Definition at line 1454 of file SystemBase.cpp.
applyRightsideTransformator() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::applyRightsideTransformator (std::vector< Eigen::Triplet< Scalar >> & triplets_transformator) protected
Definition at line 1445 of file SystemBase.cpp.
applySchriefferWolffTransformation()
template<class Scalar , class State > void SystemBase< Scalar, State >::applySchriefferWolffTransformation (SystemBase< Scalar, State > & system0)
Definition at line 975 of file SystemBase.cpp.
References SystemBase< Scalar, State >::basisvectors, SystemBase< Scalar, State >::buildHamiltonian(), SystemBase< Scalar, State >::hamiltonian, and SystemBase< Scalar, State >::states.
buildBasis()
template<class Scalar , class State > void SystemBase< Scalar, State >::buildBasis
Definition at line 526 of file SystemBase.cpp.
Referenced by SystemBase< Scalar, State >::add(), and SystemBase< Scalar, State >::getConnections().
buildHamiltonian()
template<class Scalar , class State > void SystemBase< Scalar, State >::buildHamiltonian
Methods to build, transform, and destroy the system ////////////.
Definition at line 474 of file SystemBase.cpp.
Referenced by SystemBase< Scalar, State >::applySchriefferWolffTransformation().
buildInteraction()
template<class Scalar , class State > void SystemBase< Scalar, State >::buildInteraction
Definition at line 516 of file SystemBase.cpp.
buildRotator() [1/2]
template<class Scalar , class State > Eigen::Matrix< double, 3, 3 > SystemBase< Scalar, State >::buildRotator (const double & alpha, const double & beta, const double & gamma) protected
Definition at line 1523 of file SystemBase.cpp.
buildRotator() [2/2]
template<class Scalar , class State > Eigen::Matrix< double, 3, 3 > SystemBase< Scalar, State >::buildRotator (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis) protected
Utility methods ////////////////////////////////////////////////.
Definition at line 1506 of file SystemBase.cpp.
buildStaterotator()
template<class Scalar , class State > virtual Eigen::SparseMatrix<Scalar> SystemBase< Scalar, State >::buildStaterotator (double alpha, double beta, double gamma) protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
canonicalize()
template<class Scalar , class State > void SystemBase< Scalar, State >::canonicalize
Definition at line 749 of file SystemBase.cpp.
checkIsDiagonal()
template<class Scalar , class State > bool SystemBase< Scalar, State >::checkIsDiagonal (const Eigen::SparseMatrix< Scalar > & mat) protected
Helper methods to check diagonality and unitarity of a matrix //.
Definition at line 1344 of file SystemBase.cpp.
checkIsEnergyValid()
template<class Scalar , class State > bool SystemBase< Scalar, State >::checkIsEnergyValid (double e) protected
Definition at line 1414 of file SystemBase.cpp.
checkIsQuantumnumberValid()
template<class Scalar , class State > template<class V > bool SystemBase< Scalar, State >::checkIsQuantumnumberValid (V q, std::set< V > range_q) inline protected
Helper methods to check the validity of states /////////////////.
Definition at line 332 of file SystemBase.hpp.
checkIsQuantumstateValid() [1/3]
template<class Scalar , class State > bool SystemBase< Scalar, State >::checkIsQuantumstateValid (const State & state) protected
Helper methods to check the validity of states /////////////////.
Definition at line 1385 of file SystemBase.cpp.
checkIsQuantumstateValid() [2/3]
template<class Scalar , class State > bool SystemBase< Scalar, State >::checkIsQuantumstateValid (const StateOne & state, bool a) protected
Definition at line 1390 of file SystemBase.cpp.
References StateOne::getJ(), StateOne::getL(), StateOne::getM(), and StateOne::getN().
checkIsQuantumstateValid() [3/3]
template<class Scalar , class State > bool SystemBase< Scalar, State >::checkIsQuantumstateValid (const StateTwo & state, std::array< bool, 2 > a) protected
Definition at line 1399 of file SystemBase.cpp.
References StateTwo::getJ(), StateTwo::getL(), StateTwo::getM(), and StateTwo::getN().
checkIsUnitary()
template<class Scalar , class State > bool SystemBase< Scalar, State >::checkIsUnitary (const Eigen::SparseMatrix< Scalar > & mat) protected
Definition at line 1359 of file SystemBase.cpp.
constrainBasisvectors()
template<class Scalar , class State > void SystemBase< Scalar, State >::constrainBasisvectors (std::vector< size_t > indices_of_wanted_basisvectors)
Definition at line 945 of file SystemBase.cpp.
deleteInteraction()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::deleteInteraction () protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
diagonalize() [1/4]
template<class Scalar , class State > void SystemBase< Scalar, State >::diagonalize
Definition at line 689 of file SystemBase.cpp.
diagonalize() [2/4]
template<class Scalar , class State > void SystemBase< Scalar, State >::diagonalize (double energy_lower_bound, double energy_upper_bound)
Definition at line 565 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
diagonalize() [3/4]
template<class Scalar , class State > void SystemBase< Scalar, State >::diagonalize (double energy_lower_bound, double energy_upper_bound, double threshold)
Definition at line 570 of file SystemBase.cpp.
diagonalize() [4/4]
template<class Scalar , class State > void SystemBase< Scalar, State >::diagonalize (double threshold)
Definition at line 694 of file SystemBase.cpp.
forgetStatemixing()
template<class Scalar , class State > void SystemBase< Scalar, State >::forgetStatemixing
Definition at line 1217 of file SystemBase.cpp.
getBasisvectorIndex() [1/2]
template<class Scalar , class State > size_t SystemBase< Scalar, State >::getBasisvectorIndex (const State & searched_state)
Definition at line 1128 of file SystemBase.cpp.
getBasisvectorIndex() [2/2]
template<class Scalar , class State > std::vector< size_t > SystemBase< Scalar, State >::getBasisvectorIndex (const std::vector< State > & searched_states)
Definition at line 1153 of file SystemBase.cpp.
getBasisvectors()
template<class Scalar , class State > Eigen::SparseMatrix< Scalar > & SystemBase< Scalar, State >::getBasisvectors
Definition at line 321 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
getConnections()
template<class Scalar , class State > std::array< std::vector< size_t >, 2 > SystemBase< Scalar, State >::getConnections (SystemBase< Scalar, State > & system_to, double threshold)
Definition at line 392 of file SystemBase.cpp.
References SystemBase< Scalar, State >::basisvectors, SystemBase< Scalar, State >::buildBasis(), and SystemBase< Scalar, State >::states.
getEulerAngles()
template<class Scalar , class State > Eigen::Matrix< double, 3, 1 > SystemBase< Scalar, State >::getEulerAngles (const std::array< double, 3 > & to_z_axis, const std::array< double, 3 > & to_y_axis) protected
Definition at line 1537 of file SystemBase.cpp.
getHamiltonian()
template<class Scalar , class State > Eigen::SparseMatrix< Scalar > & SystemBase< Scalar, State >::getHamiltonian
Definition at line 327 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
getHamiltonianEntry()
template<class Scalar , class State > Scalar SystemBase< Scalar, State >::getHamiltonianEntry (const State & state_row, const State & state_col)
Definition at line 1243 of file SystemBase.cpp.
getMainStates()
template<class Scalar , class State > std::vector< State > SystemBase< Scalar, State >::getMainStates
Definition at line 364 of file SystemBase.cpp.
getNumBasisvectors()
template<class Scalar , class State > size_t SystemBase< Scalar, State >::getNumBasisvectors
Definition at line 333 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
getNumStates()
template<class Scalar , class State > size_t SystemBase< Scalar, State >::getNumStates
Definition at line 349 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
getOverlap() [1/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const size_t & state_index)
Definition at line 169 of file SystemBase.cpp.
getOverlap() [2/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const size_t & state_index, double alpha, double beta, double gamma)
Definition at line 222 of file SystemBase.cpp.
getOverlap() [3/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const size_t & state_index, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 197 of file SystemBase.cpp.
getOverlap() [4/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const State & generalizedstate)
Methods to get overlaps ////////////////////////////////////////.
Definition at line 158 of file SystemBase.cpp.
getOverlap() [5/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const State & generalizedstate, double alpha, double beta, double gamma)
Definition at line 214 of file SystemBase.cpp.
getOverlap() [6/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const State & generalizedstate, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 180 of file SystemBase.cpp.
getOverlap() [7/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const std::vector< size_t > & states_indices)
Definition at line 175 of file SystemBase.cpp.
getOverlap() [8/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma)
Definition at line 262 of file SystemBase.cpp.
getOverlap() [9/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const std::vector< size_t > & states_indices, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 206 of file SystemBase.cpp.
getOverlap() [10/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const std::vector< State > & generalizedstates)
Definition at line 164 of file SystemBase.cpp.
getOverlap() [11/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const std::vector< State > & generalizedstates, double alpha, double beta, double gamma)
Definition at line 231 of file SystemBase.cpp.
getOverlap() [12/12]
template<class Scalar , class State > Eigen::VectorX< double > SystemBase< Scalar, State >::getOverlap (const std::vector< State > & generalizedstates, std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 189 of file SystemBase.cpp.
getStateIndex() [1/2]
template<class Scalar , class State > size_t SystemBase< Scalar, State >::getStateIndex (const State & searched_state)
Methods to manipulate entries of the Hamiltonian ///////////////.
Definition at line 1089 of file SystemBase.cpp.
References utils::is_true().
getStateIndex() [2/2]
template<class Scalar , class State > std::vector< size_t > SystemBase< Scalar, State >::getStateIndex (const std::vector< State > & searched_states)
Definition at line 1106 of file SystemBase.cpp.
References utils::is_true().
getStates()
template<class Scalar , class State > std::vector< State > SystemBase< Scalar, State >::getStates
Methods to get properties of the system ////////////////////////.
Definition at line 303 of file SystemBase.cpp.
getStatesMultiIndex()
template<class Scalar , class State > const states_set< State >::type & SystemBase< Scalar, State >::getStatesMultiIndex
Definition at line 315 of file SystemBase.cpp.
incorporate()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::incorporate (SystemBase< Scalar, State > & system) protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
initializeBasis()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::initializeBasis () protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
initializeInteraction()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::initializeInteraction () protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
onParameterChange()
template<class Scalar , class State > void SystemBase< Scalar, State >::onParameterChange protected
Helper method that shoul be called by the derived classes //////.
Definition at line 1313 of file SystemBase.cpp.
onStatesChange()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::onStatesChange () inline protected virtual
Reimplemented in SystemTwo< Scalar_ >.
Definition at line 290 of file SystemBase.hpp.
onSymmetryChange()
template<class Scalar , class State > void SystemBase< Scalar, State >::onSymmetryChange protected
Definition at line 1332 of file SystemBase.cpp.
range()
template<class Scalar , class State > template<class V > void SystemBase< Scalar, State >::range (std::set< V > & rset, V rmin, V rmax) inline protected
Utility methods ////////////////////////////////////////////////.
Definition at line 364 of file SystemBase.hpp.
References model_potential::V().
removeRestrictedStates()
template<class Scalar , class State > void SystemBase< Scalar, State >::removeRestrictedStates (std::function< bool(const enumerated_state< State > &)> checkIsValidEntry) protected
Definition at line 1476 of file SystemBase.cpp.
restrictEnergy()
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictEnergy (double e_min, double e_max)
Methods to restrict the number of states inside the basis //////.
Definition at line 90 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
restrictJ() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictJ (float j_min, float j_max)
Definition at line 117 of file SystemBase.cpp.
restrictJ() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictJ (std::set< float > j)
Definition at line 122 of file SystemBase.cpp.
restrictL() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictL (int l_min, int l_max)
Definition at line 107 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
restrictL() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictL (std::set< int > l)
Definition at line 112 of file SystemBase.cpp.
restrictM() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictM (float m_min, float m_max)
Definition at line 127 of file SystemBase.cpp.
restrictM() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictM (std::set< float > m)
Definition at line 132 of file SystemBase.cpp.
restrictN() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictN (int n_min, int n_max)
Definition at line 97 of file SystemBase.cpp.
Referenced by TEST_CASE_FIXTURE().
restrictN() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::restrictN (std::set< int > n)
Definition at line 102 of file SystemBase.cpp.
rotate() [1/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::rotate (double alpha, double beta, double gamma)
Definition at line 815 of file SystemBase.cpp.
rotate() [2/2]
template<class Scalar , class State > void SystemBase< Scalar, State >::rotate (std::array< double, 3 > to_z_axis, std::array< double, 3 > to_y_axis)
Definition at line 808 of file SystemBase.cpp.
rotateStates()
template<class Scalar , class State > virtual Eigen::SparseMatrix<Scalar> SystemBase< Scalar, State >::rotateStates (const std::vector< size_t > & states_indices, double alpha, double beta, double gamma) protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
setHamiltonianEntry()
template<class Scalar , class State > void SystemBase< Scalar, State >::setHamiltonianEntry (const State & state_row, const State & state_col, Scalar value)
Definition at line 1254 of file SystemBase.cpp.
References utils::conjugate().
setMinimalNorm()
template<class Scalar , class State > void SystemBase< Scalar, State >::setMinimalNorm (const double & threshold)
Definition at line 81 of file SystemBase.cpp.
transformInteraction()
template<class Scalar , class State > virtual void SystemBase< Scalar, State >::transformInteraction (const Eigen::SparseMatrix< Scalar > & transformator) protected pure virtual
Implemented in SystemTwo< Scalar_ >, and SystemOne< Scalar_ >.
unitarize()
template<class Scalar , class State > void SystemBase< Scalar, State >::unitarize
Definition at line 762 of file SystemBase.cpp.
References utils::hash_combine(), and utils::hash_range().
Friends And Related Function Documentation
cereal::access
template<class Scalar , class State > friend class cereal::access friend
Method for serialization ///////////////////////////////////////.
Definition at line 393 of file SystemBase.hpp.
Field Documentation
basisvectors
template<class Scalar , class State > Eigen::SparseMatrix<Scalar> SystemBase< Scalar, State >::basisvectors protected
Definition at line 306 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add(), SystemBase< Scalar, State >::applySchriefferWolffTransformation(), and SystemBase< Scalar, State >::getConnections().
basisvectors_unperturbed_cache
template<class Scalar , class State > Eigen::SparseMatrix<Scalar> SystemBase< Scalar, State >::basisvectors_unperturbed_cache protected
Definition at line 308 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add().
energy_max
template<class Scalar , class State > double SystemBase< Scalar, State >::energy_max protected
Definition at line 296 of file SystemBase.hpp.
energy_min
template<class Scalar , class State > double SystemBase< Scalar, State >::energy_min protected
Definition at line 296 of file SystemBase.hpp.
hamiltonian
template<class Scalar , class State > Eigen::SparseMatrix<Scalar> SystemBase< Scalar, State >::hamiltonian protected
Definition at line 307 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add(), and SystemBase< Scalar, State >::applySchriefferWolffTransformation().
hamiltonian_unperturbed_cache
template<class Scalar , class State > Eigen::SparseMatrix<Scalar> SystemBase< Scalar, State >::hamiltonian_unperturbed_cache protected
Definition at line 309 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add().
is_interaction_already_contained
template<class Scalar , class State > bool SystemBase< Scalar, State >::is_interaction_already_contained {false} protected
Definition at line 302 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add().
is_new_hamiltonian_required
template<class Scalar , class State > bool SystemBase< Scalar, State >::is_new_hamiltonian_required {false} protected
Definition at line 303 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add().
m_cache
template<class Scalar , class State > MatrixElementCache* SystemBase< Scalar, State >::m_cache {nullptr} protected
Definition at line 292 of file SystemBase.hpp.
memory_saving
template<class Scalar , class State > bool SystemBase< Scalar, State >::memory_saving {false} protected
Definition at line 301 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add().
range_j
template<class Scalar , class State > std::set<float> SystemBase< Scalar, State >::range_j protected
Definition at line 298 of file SystemBase.hpp.
range_l
template<class Scalar , class State > std::set<int> SystemBase< Scalar, State >::range_l protected
Definition at line 297 of file SystemBase.hpp.
range_m
template<class Scalar , class State > std::set<float> SystemBase< Scalar, State >::range_m protected
Definition at line 298 of file SystemBase.hpp.
range_n
template<class Scalar , class State > std::set<int> SystemBase< Scalar, State >::range_n protected
Definition at line 297 of file SystemBase.hpp.
states
template<class Scalar , class State > states_set<State>::type SystemBase< Scalar, State >::states protected
Definition at line 305 of file SystemBase.hpp.
Referenced by SystemBase< Scalar, State >::add(), SystemBase< Scalar, State >::applySchriefferWolffTransformation(), and SystemBase< Scalar, State >::getConnections().
states_to_add
template<class Scalar , class State > std::set<State> SystemBase< Scalar, State >::states_to_add protected
Definition at line 299 of file SystemBase.hpp.
threshold_for_sqnorm
template<class Scalar , class State > double SystemBase< Scalar, State >::threshold_for_sqnorm {0.05} protected
Definition at line 294 of file SystemBase.hpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/SystemBase.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/SystemBase.cpp