pairinteraction: BasisnamesOne Class Reference
BasisnamesOne Class Reference
#include <Basisnames.hpp>
Public Member Functions
const std::vector< StateOneOld > & initial () const
void removeUnnecessaryStates (const std::vector< bool > &is_necessary)
bool constructedFromFirst ()
void save (const std::string &path)
Public Member Functions inherited from Basisnames< StateOneOld >
Basisnames ()=default
void configure (const Configuration &config)
size_t size () const
size_t dim () const
StateOneOld & get (size_t idx)
const StateOneOld & get (size_t idx) const
void set (size_t i, const StateOneOld &v)
ConstIter< Basisnames, StateOneOld > begin () const
ConstIter< Basisnames, StateOneOld > end () const
const Configuration & getConf () const
Static Public Member Functions
static BasisnamesOne fromStates (const std::vector< StateOneOld > &names)
static BasisnamesOne fromFirst (const Configuration &config)
static BasisnamesOne fromFirst (const std::shared_ptr< const BasisnamesTwo > &basis_two)
static BasisnamesOne fromSecond (const Configuration &config)
static BasisnamesOne fromSecond (const std::shared_ptr< const BasisnamesTwo > &basis_two)
static BasisnamesOne fromBoth (const Configuration &config)
Additional Inherited Members
Protected Attributes inherited from Basisnames< StateOneOld >
int delta_n
int delta_l
int delta_j
int delta_m
Configuration conf
std::vector< StateOneOld > names_
size_t dim_
Detailed Description
Definition at line 71 of file Basisnames.hpp.
Member Function Documentation
constructedFromFirst()
bool BasisnamesOne::constructedFromFirst ()
Definition at line 283 of file Basisnames.cpp.
fromBoth()
BasisnamesOne BasisnamesOne::fromBoth (const Configuration & config) static
Definition at line 84 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateTwoOld::j, StateTwoOld::l, StateTwoOld::m, StateTwoOld::n, and StateTwoOld::order().
Referenced by compute().
fromFirst() [1/2]
BasisnamesOne BasisnamesOne::fromFirst (const Configuration & config) static
Definition at line 30 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
Referenced by HamiltonianTwo< Scalar >::calculate(), and compute().
fromFirst() [2/2]
BasisnamesOne BasisnamesOne::fromFirst (const std::shared_ptr< const BasisnamesTwo > & basis_two) static
Definition at line 43 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
fromSecond() [1/2]
BasisnamesOne BasisnamesOne::fromSecond (const Configuration & config) static
Definition at line 57 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
Referenced by HamiltonianTwo< Scalar >::calculate(), and compute().
fromSecond() [2/2]
BasisnamesOne BasisnamesOne::fromSecond (const std::shared_ptr< const BasisnamesTwo > & basis_two) static
Definition at line 70 of file Basisnames.cpp.
References Basisnames< T >::configure(), StateOneOld::j, StateOneOld::l, StateOneOld::m, and StateOneOld::n.
fromStates()
BasisnamesOne BasisnamesOne::fromStates (const std::vector< StateOneOld > & names) static
Definition at line 24 of file Basisnames.cpp.
References Basisnames< T >::dim_, and Basisnames< T >::names_.
initial()
const std::vector< StateOneOld > & BasisnamesOne::initial () const
Definition at line 262 of file Basisnames.cpp.
removeUnnecessaryStates()
void BasisnamesOne::removeUnnecessaryStates (const std::vector< bool > & is_necessary)
Definition at line 263 of file Basisnames.cpp.
References Basisnames< StateOneOld >::dim_, and Basisnames< StateOneOld >::names_.
save()
void BasisnamesOne::save (const std::string & path)
Definition at line 285 of file Basisnames.cpp.
The documentation for this class was generated from the following files:
/__w/pairinteraction/pairinteraction/pairinteraction/Basisnames.hpp
/__w/pairinteraction/pairinteraction/pairinteraction/Basisnames.cpp