pairinteraction: /__w/pairinteraction/pairinteraction/pairinteraction/Interface.cpp File Reference
Interface.cpp File Reference
#include "Interface.hpp"
#include "ConfParser.hpp"
#include "HamiltonianOne.hpp"
#include "HamiltonianTwo.hpp"
#include "filesystem.hpp"
#include <fmt/format.h>
#include <iostream>
#include <locale>
#include <memory>
Functions
template<typename Scalar >
int compute (const std::string &config_name, const std::string &output_name)
template int compute< std::complex< double > > (std::string const &config_name, std::string const &output_name)
template int compute< double > (std::string const &config_name, std::string const &output_name)
Function Documentation
compute()
template<typename Scalar > int compute (const std::string & config_name, const std::string & output_name)
Definition at line 42 of file Interface.cpp.
References Configuration::count(), BasisnamesOne::fromBoth(), BasisnamesOne::fromFirst(), BasisnamesOne::fromSecond(), and Configuration::load_from_json().
compute< double >()
template int compute< double > (std::string const & config_name, std::string const & output_name)
compute< std::complex< double > >()
template int compute< std::complex< double > > (std::string const & config_name, std::string const & output_name)