pairinteraction: /__w/pairinteraction/pairinteraction/pairinteraction/MatrixElementCache.cpp File Reference
MatrixElementCache.cpp File Reference
#include "MatrixElementCache.hpp"
#include "Constants.hpp"
#include "QuantumDefect.hpp"
#include "SQLite.hpp"
#include "filesystem.hpp"
#include "utils.hpp"
#include "version.hpp"
#include <boost/tokenizer.hpp>
#include <cctype>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
Functions
bool selectionRulesMomentumNew (StateOne const &state1, StateOne const &state2, int q)
bool selectionRulesMomentumNew (StateOne const &state1, StateOne const &state2)
bool selectionRulesMultipoleNew (StateOne const &state1, StateOne const &state2, int kappa, int q)
bool selectionRulesMultipoleNew (StateOne const &state1, StateOne const &state2, int kappa)
Function Documentation
selectionRulesMomentumNew() [1/2]
bool selectionRulesMomentumNew (StateOne const & state1, StateOne const & state2)
Definition at line 47 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
selectionRulesMomentumNew() [2/2]
bool selectionRulesMomentumNew (StateOne const & state1, StateOne const & state2, int q)
Definition at line 39 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
Referenced by SystemOne< Scalar_ >::initializeInteraction().
selectionRulesMultipoleNew() [1/2]
bool selectionRulesMultipoleNew (StateOne const & state1, StateOne const & state2, int kappa)
Definition at line 67 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
selectionRulesMultipoleNew() [2/2]
bool selectionRulesMultipoleNew (StateOne const & state1, StateOne const & state2, int kappa, int q)
Definition at line 54 of file MatrixElementCache.cpp.
References StateOne::getJ(), StateOne::getL(), and StateOne::getM().
Referenced by SystemOne< Scalar_ >::initializeInteraction(), and SystemTwo< Scalar_ >::initializeInteraction().