pairinteraction: /__w/pairinteraction/pairinteraction/pairinteraction/MatrixElements.hpp File Reference
MatrixElements.hpp File Reference
#include "Basisnames.hpp"
#include "StateOld.hpp"
#include "Wavefunction.hpp"
#include <wignerSymbols/wignerSymbols-cpp.h>
#include <memory>
#include <sstream>
#include <string>
#include <unordered_map>
Data Structures
class MatrixElements
Functions
bool selectionRulesMomentum (StateOneOld const &state1, StateOneOld const &state2, int q)
bool selectionRulesMomentum (StateOneOld const &state1, StateOneOld const &state2)
bool selectionRulesMultipole (StateOneOld const &state1, StateOneOld const &state2, int kappa, int q)
bool selectionRulesMultipole (StateOneOld const &state1, StateOneOld const &state2, int kappa)
Function Documentation
selectionRulesMomentum() [1/2]
bool selectionRulesMomentum (StateOneOld const & state1, StateOneOld const & state2)
Definition at line 44 of file MatrixElements.cpp.
References StateOneOld::j, StateOneOld::l, and StateOneOld::m.
selectionRulesMomentum() [2/2]
bool selectionRulesMomentum (StateOneOld const & state1, StateOneOld const & state2, int q)
Definition at line 36 of file MatrixElements.cpp.
References StateOneOld::j, StateOneOld::l, and StateOneOld::m.
Referenced by HamiltonianOne< Scalar >::build().
selectionRulesMultipole() [1/2]
bool selectionRulesMultipole (StateOneOld const & state1, StateOneOld const & state2, int kappa)
Definition at line 63 of file MatrixElements.cpp.
References StateOneOld::j, StateOneOld::l, and StateOneOld::m.
selectionRulesMultipole() [2/2]
bool selectionRulesMultipole (StateOneOld const & state1, StateOneOld const & state2, int kappa, int q)
Definition at line 51 of file MatrixElements.cpp.
References StateOneOld::j, StateOneOld::l, and StateOneOld::m.
Referenced by HamiltonianOne< Scalar >::build(), and HamiltonianTwo< Scalar >::calculate().