pairinteraction: utils Namespace Reference
utils Namespace Reference
Data Structures
struct hash< enumerated_state< T > >
struct is_complex
struct is_complex< std::complex< S > >
struct hash
Hash function.
struct hash< std::array< T, N > >
struct hash< std::complex< T > >
Functions
template<typename T >
T conjugate (const T &val)
template<typename S >
std::complex< S > conjugate (const std::complex< S > &val)
template<typename T >
bool is_true (const T &val)
bool is_true (bool val)
template<typename T >
std::enable_if<!is_complex< T >::value, T >::type imaginary_unit ()
template<typename T >
std::enable_if< is_complex< T >::value, T >::type imaginary_unit ()
template<typename T , typename U >
T convert (const U &val)
template<typename S >
S convert (const std::complex< S > &val)
std::default_random_engine & randint_engine ()
Thread-local static random engine.
template<typename T >
T randint (T a, T b)
Generate a random integer.
uint64_t FNV64 (const uint8_t *s, size_t sz)
long get_pid ()
template<typename T >
void hash_combine (std::size_t &seed, T const &v)
Combine hashes.
template<typename It >
std::size_t hash_range (It first, It last)
Combine hashes of values in a range.
Function Documentation
conjugate() [1/2]
template<typename S > std::complex<S> utils::conjugate (const std::complex< S > & val) inline
Definition at line 48 of file utils.hpp.
conjugate() [2/2]
template<typename T > T utils::conjugate (const T & val) inline
Definition at line 44 of file utils.hpp.
Referenced by SystemBase< Scalar, State >::addHamiltonianEntry(), and SystemBase< Scalar, State >::setHamiltonianEntry().
convert() [1/2]
template<typename S > S utils::convert (const std::complex< S > & val) inline
Definition at line 73 of file utils.hpp.
convert() [2/2]
template<typename T , typename U > T utils::convert (const U & val) inline
Definition at line 69 of file utils.hpp.
FNV64()
uint64_t utils::FNV64 (const uint8_t * s, size_t sz) inline
Definition at line 110 of file utils.hpp.
Referenced by Hamiltonianmatrix< Scalar >::hashBasis(), and Hamiltonianmatrix< Scalar >::hashEntries().
get_pid()
long utils::get_pid () inline
Definition at line 120 of file utils.hpp.
hash_combine()
template<typename T > void utils::hash_combine (std::size_t & seed, T const & v) inline
Combine hashes.
The implementation of hash_combine is copied from Boost but simplified. It uses the custom hash.
Parameters
seed start hash
v value whose hash is to be added to seed
Definition at line 147 of file utils.hpp.
Referenced by hash_range(), std::hash< StateOneOld >::operator()(), std::hash< StateTwoOld >::operator()(), utils::hash< std::complex< T > >::operator()(), StateOne::StateOne(), and SystemBase< Scalar, State >::unitarize().
hash_range()
template<typename It > std::size_t utils::hash_range (It first, It last) inline
Combine hashes of values in a range.
Parameters
first forward iterator
last forward iterator
Returns
combined hash of all values in the range
Definition at line 158 of file utils.hpp.
References hash_combine().
Referenced by utils::hash< std::array< T, N > >::operator()(), and SystemBase< Scalar, State >::unitarize().
imaginary_unit() [1/2]
template<typename T > std::enable_if<!is_complex<T>::value, T>::type utils::imaginary_unit () inline
Definition at line 59 of file utils.hpp.
imaginary_unit() [2/2]
template<typename T > std::enable_if<is_complex<T>::value, T>::type utils::imaginary_unit () inline
Definition at line 64 of file utils.hpp.
is_true() [1/2]
bool utils::is_true (bool val) inline
Definition at line 56 of file utils.hpp.
is_true() [2/2]
template<typename T > bool utils::is_true (const T & val) inline
Definition at line 53 of file utils.hpp.
Referenced by SystemBase< Scalar, State >::getStateIndex(), and SystemBase< Scalar_, StateTwo >::rotate().
randint()
template<typename T > T utils::randint (T a, T b) inline
Generate a random integer.
This is very similar to the implementation of randint in the GCC standard library Fundamentals TS v2. It is specified by the standard per clause 13.2.2.1, Function template randint.
The function generates a random integer in the closed interval [a,b].
Parameters
a lower bound
b upper bound
Returns
random integer between a and b.
Definition at line 104 of file utils.hpp.
References randint_engine().
Referenced by TEST_CASE().
randint_engine()
std::default_random_engine& utils::randint_engine () inline
Thread-local static random engine.
To save some effort this function initializes a static thread-local random engine to avoid race conditions and broken random sampling. It is seeded once using std::random_device for good entropy.
Returns
Reference to static thread-local random engine
Definition at line 85 of file utils.hpp.
Referenced by randint().