pairinteraction: numpy::internal Namespace Reference
numpy::internal Namespace Reference
Data Structures
struct py_type
Map C++ types to Numpy types.
struct py_type< int >
Specialization of py_type for int.
struct py_type< float >
Specialization of py_type for float.
struct py_type< double >
Specialization of py_type for double.
struct py_type< std::complex< double > >
Specialization of py_type for double.
Functions
template<typename T >
void check_array_sanity (int len, int nd, std::initializer_list< T > dims)
Perform sanity checks for convert.
template<view_or_copy v, bool const_tag, typename value_type >
std::enable_if< v==numpy::view, PyObject * >::type convert_impl (int nd, npy_intp *dim, int dtype, void *data, int)
Create a Numpy view of an iterator (implementation)
template<view_or_copy v, bool const_tag, typename value_type >
std::enable_if< v==numpy::copy, PyObject * >::type convert_impl (int nd, npy_intp *dim, int dtype, void *data, int len)
Create a Numpy copy of an iterator (implementation)
template<view_or_copy v, typename RAIter , typename T >
PyObject * convert (RAIter begin, RAIter end, int nd, std::initializer_list< T > dims, std::random_access_iterator_tag)
Create a Numpy array from an iterator (implementation)
template<view_or_copy v, typename T >
PyObject * sparse_impl (T &&sm)
Create a Numpy array from an Eigen::SparseMatrix.
void check_order_and_alignment (PyArrayObject *ndarray)
Check if a Numpy has given storage order and alignment.
template<typename T , typename Scalar = typename T::Scalar>
std::tuple< int, npy_intp *, Scalar * > as_dense_impl (numpy::array ndarray_)
Deconstruct a numpy array for conversion to dense Eigen type.
Function Documentation
as_dense_impl()
template<typename T , typename Scalar = typename T::Scalar> std::tuple<int, npy_intp *, Scalar *> numpy::internal::as_dense_impl (numpy::array ndarray_)
Deconstruct a numpy array for conversion to dense Eigen type.
Parameters
[in] ndarray_ Numpy array
Returns
A tuple of the number of dimensions, an array of dimensions, and a pointer to the data.
Definition at line 408 of file NumpyUtils.hpp.
References check_order_and_alignment().
check_array_sanity()
template<typename T > void numpy::internal::check_array_sanity (int len, int nd, std::initializer_list< T > dims)
Perform sanity checks for convert.
To ensure that dimensions and types are consistent we introduce this check function.
Parameters
[in] len Length of the memory
[in] nd Number of dimensions
[in] dims Initializer list with lengths of dimensions
Returns
The total length of the array
Definition at line 106 of file NumpyUtils.hpp.
Referenced by convert().
check_order_and_alignment()
void numpy::internal::check_order_and_alignment (PyArrayObject * ndarray)
Check if a Numpy has given storage order and alignment.
To be convertible to an Eigen matrix type the memory of a Numpy array has to be FORTRAN style contiguous and has to be aligned.
Parameters
[in] ndarray Numpy array
Definition at line 392 of file NumpyUtils.hpp.
Referenced by numpy::as(), and as_dense_impl().
convert()
template<view_or_copy v, typename RAIter , typename T > PyObject* numpy::internal::convert (RAIter begin, RAIter end, int nd, std::initializer_list< T > dims, std::random_access_iterator_tag)
Create a Numpy array from an iterator (implementation)
This is the implementation for the conversion of an arbitrary pointer between begin and end .
Parameters
[in] begin Random access iterator pointing to the start
[in] end Random access iterator pointing to the end
[in] nd Number of dimensions
[in] dims Initializer list with lengths of dimensions
Returns
PyObject* containing a Numpy array
Definition at line 182 of file NumpyUtils.hpp.
References check_array_sanity().
convert_impl() [1/2]
template<view_or_copy v, bool const_tag, typename value_type > std::enable_if<v == numpy::copy, PyObject *>::type numpy::internal::convert_impl (int nd, npy_intp * dim, int dtype, void * data, int len)
Create a Numpy copy of an iterator (implementation)
This creates a copy of the data, i.e. the data belongs to the Python end. The array is marked with NPY_OWNDATA which should tell the garbage collector to release this memory.
Parameters
[in] nd Number of dimensions
[in] dim Dimensions of the array
[in] dtype Value type of array elements
[in] data Pointer to array data
[in] len Length of data
Returns
PyObject* containing a Numpy array
Definition at line 159 of file NumpyUtils.hpp.
convert_impl() [2/2]
template<view_or_copy v, bool const_tag, typename value_type > std::enable_if<v == numpy::view, PyObject *>::type numpy::internal::convert_impl (int nd, npy_intp * dim, int dtype, void * data, int)
Create a Numpy view of an iterator (implementation)
This creates a view of the data, i.e. the data still belongs to the C++ end. When the data is deallocated on the C++ end trying to access it in Python will probably cause a segfault. In any case it is undefined behavior.
Parameters
[in] nd Number of dimensions
[in] dim Dimensions of the array
[in] dtype Value type of array elements
[in] data Pointer to array data
Returns
PyObject* containing a Numpy array
Definition at line 134 of file NumpyUtils.hpp.
sparse_impl()
template<view_or_copy v, typename T > PyObject* numpy::internal::sparse_impl (T && sm)
Create a Numpy array from an Eigen::SparseMatrix.
This is the implementation for the conversion of an Eigen::SparseMatrix to a scipy.sparse.csc_matrix. We load the scipy.sparse module and call the constructor for the csc_matrix which we populate with numpy arrays.
Parameters
[in] sm T&&
Returns
PyObject* containing a Scipy csc_matrix
Definition at line 328 of file NumpyUtils.hpp.