pairinteraction: pairinteraction::euler Namespace Reference
pairinteraction::euler Namespace Reference
Functions
template<typename Real >
Eigen::Matrix3< Real > get_rotation_matrix (std::array< Real, 3 > to_z_axis, std::array< Real, 3 > to_y_axis)
Build a matrix that rotates the coordinate system to the new z-axis and y-axis.
template<typename Real >
std::array< Real, 3 > get_euler_angles (std::array< Real, 3 > to_z_axis, std::array< Real, 3 > to_y_axis)
Extract the Euler angles alpha, beta, gamma.
Function Documentation
get_euler_angles()
template<typename Real > std::array< Real, 3 > pairinteraction::euler::get_euler_angles (std::array< Real, 3 > to_z_axis, std::array< Real, 3 > to_y_axis) inline
Extract the Euler angles alpha, beta, gamma.
@function get_euler_angles
Template Parameters
Real The type of a real number.
Parameters
to_z_axis The new z-axis.
to_y_axis The new y-axis.
Returns
The Euler angles.
Definition at line 64 of file euler.hpp.
References get_rotation_matrix().
Referenced by pairinteraction::TransformationBuilderInterface< Scalar >::get_rotator().
get_rotation_matrix()
template<typename Real > Eigen::Matrix3< Real > pairinteraction::euler::get_rotation_matrix (std::array< Real, 3 > to_z_axis, std::array< Real, 3 > to_y_axis) inline
Build a matrix that rotates the coordinate system to the new z-axis and y-axis.
@function get_rotation_matrix
Template Parameters
Real The type of a real number.
Parameters
to_z_axis The new z-axis.
to_y_axis The new y-axis.
Returns
The passive rotation matrix.
Definition at line 29 of file euler.hpp.
Referenced by get_euler_angles().