pairinteraction: pairinteraction::paths Namespace Reference
pairinteraction::paths Namespace Reference
Functions
std::filesystem::path get_home_directory ()
std::filesystem::path get_cache_directory ()
std::filesystem::path get_config_directory ()
Function Documentation
get_cache_directory()
std::filesystem::path pairinteraction::paths::get_cache_directory () inline
Definition at line 29 of file paths.hpp.
References get_home_directory().
Referenced by bind_paths(), LoggerBridge::LoggerBridge(), pairinteraction::run_unit_tests(), and pairinteraction::setup().
get_config_directory()
std::filesystem::path pairinteraction::paths::get_config_directory () inline
Definition at line 61 of file paths.hpp.
References get_home_directory().
Referenced by bind_paths(), pairinteraction::Database::Database(), and pairinteraction::GitHubDownloader::GitHubDownloader().
get_home_directory()
std::filesystem::path pairinteraction::paths::get_home_directory () inline
Definition at line 11 of file paths.hpp.
Referenced by get_cache_directory(), and get_config_directory().