pairinteraction: /__w/pairinteraction/pairinteraction/src/cpp/src/database/ParquetManager.cpp File Reference
ParquetManager.cpp File Reference
#include "pairinteraction/database/ParquetManager.hpp"
#include "pairinteraction/database/GitHubDownloader.hpp"
#include "pairinteraction/version.hpp"
#include <cpptrace/cpptrace.hpp>
#include <ctime>
#include <duckdb.hpp>
#include <filesystem>
#include <fmt/core.h>
#include <fstream>
#include <future>
#include <iomanip>
#include <miniz.h>
#include <nlohmann/json.hpp>
#include <regex>
#include <set>
#include <spdlog/spdlog.h>
#include <sstream>
#include <stdexcept>
#include <string>
Namespaces
namespace pairinteraction
Typedefs
using json = nlohmann::json
Functions
std::string format_time (std::time_t time_val)
json load_json (const fs::path &file)
void save_json (const fs::path &file, const json &doc)
Typedef Documentation
json
using json = nlohmann::json
Definition at line 27 of file ParquetManager.cpp.
Function Documentation
format_time()
std::string format_time (std::time_t time_val)
Definition at line 29 of file ParquetManager.cpp.
Referenced by pairinteraction::ParquetManager::ParquetManager().
load_json()
json load_json (const fs::path & file)
Definition at line 36 of file ParquetManager.cpp.
Referenced by pairinteraction::ParquetManager::scan_remote().
save_json()
void save_json (const fs::path & file, const json & doc)
Definition at line 44 of file ParquetManager.cpp.
Referenced by pairinteraction::ParquetManager::scan_remote().