pairinteraction: doctest::LoggingReporter Struct Reference
doctest::LoggingReporter Struct Reference
Public Member Functions
LoggingReporter (const ContextOptions &co)
void log_contexts ()
void logTestStart ()
void test_run_end (const TestRunStats &p) override
void test_case_end (const CurrentTestCaseStats &st) override
void test_case_exception (const TestCaseException &e) override
void log_assert (const AssertData &rb) override
void log_message (const MessageData &mb) override
Detailed Description
Definition at line 35 of file run_unit_tests.cpp.
Constructor & Destructor Documentation
LoggingReporter()
doctest::LoggingReporter::LoggingReporter (const ContextOptions & co) inline
Definition at line 36 of file run_unit_tests.cpp.
Member Function Documentation
log_assert()
void doctest::LoggingReporter::log_assert (const AssertData & rb) inline override
Definition at line 175 of file run_unit_tests.cpp.
References DOCTEST_LOCK_MUTEX, log_contexts(), and logTestStart().
log_contexts()
void doctest::LoggingReporter::log_contexts () inline
Definition at line 38 of file run_unit_tests.cpp.
Referenced by log_assert(), and log_message().
log_message()
void doctest::LoggingReporter::log_message (const MessageData & mb) inline override
Definition at line 203 of file run_unit_tests.cpp.
References DOCTEST_LOCK_MUTEX, log_contexts(), and logTestStart().
logTestStart()
void doctest::LoggingReporter::logTestStart () inline
Definition at line 40 of file run_unit_tests.cpp.
Referenced by log_assert(), log_message(), test_case_end(), and test_case_exception().
test_case_end()
void doctest::LoggingReporter::test_case_end (const CurrentTestCaseStats & st) inline override
Definition at line 98 of file run_unit_tests.cpp.
References logTestStart().
test_case_exception()
void doctest::LoggingReporter::test_case_exception (const TestCaseException & e) inline override
Definition at line 154 of file run_unit_tests.cpp.
References DOCTEST_LOCK_MUTEX, and logTestStart().
test_run_end()
void doctest::LoggingReporter::test_run_end (const TestRunStats & p) inline override
Definition at line 42 of file run_unit_tests.cpp.
The documentation for this struct was generated from the following file:
/__w/pairinteraction/pairinteraction/src/cpp/src/tools/run_unit_tests.cpp