pairinteraction: /__w/pairinteraction/pairinteraction/src/cpp/tests/test_pair_potential.cpp File Reference
test_pair_potential.cpp File Reference
#include "pairinteraction/pairinteraction.hpp"
#include "pairinteraction/utils/args.hpp"
#include <Eigen/Dense>
#include <filesystem>
#include <fstream>
#include <spdlog/spdlog.h>
#include <vector>
Functions
int main (int argc, char **argv)
Variables
constexpr double HARTREE_IN_GHZ = 6579683.920501762
constexpr double UM_IN_ATOMIC_UNITS = 1 / 5.29177210544e-5
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 16 of file test_pair_potential.cpp.
References pairinteraction::BasisPairCreator< Scalar >::add(), pairinteraction::KetAtomCreator::create(), pairinteraction::diagonalize(), pairinteraction::FLOAT32, pairinteraction::System< Derived >::get_sorter(), HARTREE_IN_GHZ, pairinteraction::args::parse_data_dir(), pairinteraction::args::parse_database_dir(), pairinteraction::args::parse_download_missing(), pairinteraction::SystemPair< Scalar >::set_distance_vector(), pairinteraction::KetAtomCreator::set_quantum_number_l(), pairinteraction::KetAtomCreator::set_quantum_number_m(), pairinteraction::KetAtomCreator::set_quantum_number_n(), pairinteraction::BasisAtomCreator< Scalar >::set_species(), pairinteraction::KetAtomCreator::set_species(), pairinteraction::setup(), pairinteraction::SORT_BY_ENERGY, pairinteraction::System< Derived >::transform(), and UM_IN_ATOMIC_UNITS.
Variable Documentation
HARTREE_IN_GHZ
constexpr double HARTREE_IN_GHZ = 6579683.920501762 constexpr
Definition at line 13 of file test_pair_potential.cpp.
Referenced by main().
UM_IN_ATOMIC_UNITS
constexpr double UM_IN_ATOMIC_UNITS = 1 / 5.29177210544e-5 constexpr
Definition at line 14 of file test_pair_potential.cpp.
Referenced by main().