name: setup-vcpkg

runs:
  using: "composite"
  steps:
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: false

    - name: Export CMAKE_TOOLCHAIN_FILE
      shell: pwsh
      run: echo "CMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" >> $env:GITHUB_ENV

    - name: Specify where DLLs will be installed
      shell: pwsh
      run: echo "VCPKG_INSTALLED_DIR=$env:GITHUB_WORKSPACE\vcpkg_installed" >> $env:GITHUB_ENV

    - name: Make the installed DLLs visible
      shell: pwsh
      run: echo "PATH=$env:VCPKG_INSTALLED_DIR\x64-windows\bin;$env:PATH" >> $env:GITHUB_ENV
