name: Schedule

# Scheduled workflows don't automatically run on forks, which actually disables
# the entire workflow altogether, so we have this extra workflow whose only
# purpose is to trigger other workflows on a schedule.

on:
  schedule:
  - cron: '0 0 * * 1' # Every Monday at 00:00

jobs:
  cpp-backend:
    uses: ./.github/workflows/cpp-backend.yml
  python-wheel:
    uses: ./.github/workflows/python-wheel.yml
